### ISSUE TITLE
hardhat(forking mainnet) revert without anything explicit error

### ISSUE THREAD

**Issue by Hasiwansui** [nomiclabs/hardhat#1464] opened 2021-05-18 18:04 UTC
Hi guys.
When my solidity code run to this place

```solidity
        (address token0, address token1) = sortTokens(tokenA, tokenB);
        address pair1 = address(uint(keccak256(abi.encodePacked(hex'ff',UNIFAC,keccak256(abi.encodePacked(token0, token1)),hex'96e8ac4277198ff8b6f785478aa9a39f403cb768dd02cbee326c3e7da348845f')))); // init code hash
        console.log("pair1:",pair1);

        address pair2 = address(uint(keccak256(abi.encodePacked(hex'ff',SUSHIFAC,keccak256(abi.encodePacked(token0, token1)),hex'e18a34eb0e04b04f7a0ac29a6e80748dca96319b42c54d679cb821dca90c6303'))));
        console.log("pair2:",pair2);
        if(pair == pair1){
            return true;
        } 
        console.log("not 1");
        if(pair == pair2){
            return true;
        }

        return false;
```

It reverts after logging “not 1”，and here is the log of the output and debugger
>Mined block #12455661
>  Block: 0x0580d0fa1f3781703bfbc4001590f34ad493d56d874ba646559ae4f47d54e3ae
>    Transaction:             0x5ddf1f1f3a37fb9bbbff543e31bf73035f32d90014f1253ca3c5cafc9949ed64
>      Contract call:         UniFlashSwap#callWithGastoken
>      From:                  0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
>      To:                    0xe6e340d132b5f46d1e472debcd681b2abc16e57e
>      Value:                 0 ETH
>      Gas used:              110677 of 9032984

###      console.log:
>        sender:  0xe6e340d132b5f46d1e472debcd681b2abc16e57e
>        amount0:  0
>        amount1:  300000000000000000000
>        bribe: 100
>        address:  0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 0xfca59cd816ab1ead66534d82bc21e7515ce441cf >0x53aabccae8c1713a6a150d9981d2ee867d0720e8
>        pair1: 0x86fef14c27c78deaeb4349fd959caa11fc5b5d75
>        pair2: 0x53aabccae8c1713a6a150d9981d2ee867d0720e8
>        not 1

###      Error: VM Exception while processing transaction: revert call unsuccess
>          at UniFlashSwap.uniswapV2Call (contracts/flash.sol:130)
>          at HardhatNode._mineBlockWithPendingTxs (/home/piepile/arbapp/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1154:23)
>          at HardhatNode.mineBlock (/home/piepile/arbapp/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:377:16)
>          at HardhatModule._intervalMineAction (/home/piepile/arbapp/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/modules/hardhat.ts:129:20)
>          at HardhatNetworkProvider._sendWithLogging (/home/piepile/arbapp/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:119:22)
>          at HardhatNetworkProvider.request (/home/piepile/arbapp/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:99:18)
>          at MiningTimer._mineFunction (/home/piepile/arbapp/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:304:9)
>          at MiningTimer._loop (/home/piepile/arbapp/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/MiningTimer.ts:98:5)

and here is the network settings of my config

```typescript
networks:{
    hardhat:{
      forking:{
        url:"API-KEY"
      },
      mining:{
        auto:false,
        interval:2000
      },
      gas:10000000,
      gasPrice:0,
      throwOnTransactionFailures:true,
      throwOnCallFailures:true,
      loggingEnabled:true
    },
  }
```

**Comment by fvictorio** [comment] 2021-05-18 18:56
This line in the stack trace:

```
     at UniFlashSwap.uniswapV2Call (contracts/flash.sol:130)
```

makes me think that the error is caused by a post-condition in a flash loan not being satisfied. If that's the case, the problem isn't in hardhat, but in your contract's code.

I'm going to assume that's the case and close this issue. Please re-open if you think that this is a problem with Hardhat (and keep in mind that "the error could've been more helpful" is something we consider a problem, so feel free to re-open in that case too). If you have further questions, you can also use [our discord server](https://hardhat.org/discord)

**Closed by fvictorio** 2021-05-18 18:56 UTC

**Comment by Hasiwansui** [comment] 2021-05-18 19:55
> This line in the stack trace:
> 
> ```
>      at UniFlashSwap.uniswapV2Call (contracts/flash.sol:130)
> ```
> 
> makes me think that the error is caused by a post-condition in a flash loan not being satisfied. If that's the case, the problem isn't in hardhat, but in your contract's code.
> 
> I'm going to assume that's the case and close this issue. Please re-open if you think that this is a problem with Hardhat (and keep in mind that "the error could've been more helpful" is something we consider a problem, so feel free to re-open in that case too). If you have further questions, you can also use [our discord server](https://hardhat.org/discord)

I had simulated with same parameters on the   
same block using tenderly and the transaction succeed. This function's return value is wrapped by a require and the debugger didn't throw that require's error message.So the function could just reverted after "not 1" log inside this function til it throwing return value.But there just an if condition clause and I can't figure out what happened.

**Comment by fvictorio** [comment] 2021-05-19 14:27
In that case there is a chance this is a bug in hardhat. If you can make a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), please share it here and I'll reopen the issue.
