### ISSUE TITLE
`hardhat_setStorageAt` fails with `InvalidArgumentsError` in some cases

### ISSUE THREAD

**Issue by mds1** [nomiclabs/hardhat#1700] opened 2021-07-20 17:48 UTC
I was playing around with `hardhat_setStorageAt` and it seems there is a bug. Here's a code snippet to reproduce. What I'm doing here is overwriting storage to set token balance to zero just as a test of the functionality.

Code to reproduce:

```typescript
import { ethers } from 'hardhat';
import { keccak256 } from '@ethersproject/keccak256';
const { defaultAbiCoder } = ethers.utils;

// Helper method to get token balance of a user
async function balanceOf(tokenAddress: string, user: string) {
  const abi = ['function balanceOf(address) external view returns (uint256)'];
  const contract = new ethers.Contract(tokenAddress, abi, ethers.provider);
  return (await contract.balanceOf(user)).toString();
}

// Define parameters needed to set balance to 0
const curveTricryptoAddress = '0xD51a44d3FaE010294C616388b506AcdA1bfAAE46'; // mainnet Curve Tricrypto pool
const usdt = '0xdAC17F958D2ee523a2206206994597C13D831ec7';
const wbtc = '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599';
const usdtSlot = keccak256(defaultAbiCoder.encode(['address', 'uint256'], [curveTricryptoAddress, '0x2'])); // balances start in slot 2
const wbtcSlot = keccak256(defaultAbiCoder.encode(['address', 'uint256'], [curveTricryptoAddress, '0x0'])); // balances start in slot 0
const newBalance = '0x0000000000000000000000000000000000000000000000000000000000000000'

// Set USDT and it works
console.log('USDT balance start: ', await balanceOf(usdt, curveTricryptoAddress)); // 5153844403558
await network.provider.send('hardhat_setStorageAt', [usdt, usdtSlot, newBalance]);
console.log('USDT balance end: ', await balanceOf(usdt, curveTricryptoAddress)); // 0
      

// Set WBTC and it errors with the stack trace below
console.log('WBTC balance start: ', await balanceOf(wbtc, curveTricryptoAddress)); // 17391500043
await network.provider.send('hardhat_setStorageAt', [wbtc, wbtcSlot, newBalance]); // errors here
console.log('WBTC balance end: ', await balanceOf(wbtc, curveTricryptoAddress)); // never gets here
```

And here is the resulting stack trace

```
InvalidArgumentsError: Errors encountered in param 1: Invalid value "0x041fb92791af656a5970d946eab0726fa7cc29ad5366ae52491c17c2fe5efcb1" supplied to : QUANTITY
      at Object.validateParams (node_modules/hardhat/src/internal/core/jsonrpc/types/input/validation.ts:64:13)
      at HardhatModule._setStorageAtParams (node_modules/hardhat/src/internal/hardhat-network/provider/modules/hardhat.ts:275:45)
      at HardhatModule.processRequest (node_modules/hardhat/src/internal/hardhat-network/provider/modules/hardhat.ts:102:49)
      at HardhatNetworkProvider._send (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:198:35)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:105:18)
      at Context.<anonymous> (test/YearnCrvTricrypto.test.ts:314:7)
```

And finally, proof that the storage slot is correct, using seth:

```sh
$ seth --to-dec $(seth storage 0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599 0x041fb92791af656a5970d946eab0726fa7cc29ad5366ae52491c17c2fe5efcb1)
17391500043 # outputs this, which is correct
```

**Comment by fvictorio** [comment] 2021-07-20 18:38
As @alcuadrado mentioned in the [Discord server](https://hardhat.org/discord), this is caused by the leading zero in the value. I'm going to close this in favor of https://github.com/nomiclabs/hardhat/issues/1585, where we are discussing what to do about this.

**Closed by fvictorio** 2021-07-20 18:38 UTC

**Comment by laizy** [comment] 2021-08-25 06:42
@fvictorio the storage‘s key/value in ethereum is fixed 20 bytes, and should be encoded as Hash. There is nothing to do with integer encoding, and leading zero should not be removed.

Here is the signature from ethereuem's go code :
```
func (ec *Client) StorageAt(ctx context.Context, account common.Address, key common.Hash, blockNumber *big.Int) ([]byte, error) 
```

The `eth_getStorageAt` api has  this problem too, and will report error if I use go client to send request to hardhat node:

```
---> {"jsonrpc":"2.0","id":17,"method":"eth_getStorageAt","params":["0x851356ae760d987e095750cceb3bc6014560891c","0x0000000000000000000000000000000000000000000000000000000000000001","latest"]}
<--- {"code":-32602,"message":"Errors encountered in param 1: Invalid value \"0x0000000000000000000000000000000000000000000000000000000000000001\" supplied to : QUANTITY"}
```

**Comment by fvictorio** [comment] 2021-08-25 16:17
@laizy that's true, but that's a lower-level layer. In the JSON-RPC layer, things might use different types. For example, if you make an `eth_call` to a contract that returns a `uint` of value 1, the answer will be `0x1`, not `0x0000000000000000000000000000000000000000000000000000000000000001`. That kind of value has a (somewhat) well defined format, and that doesn't allow leading zeros.

**Comment by fvictorio** [comment] 2021-08-25 16:18
Oh, and you could argue that for a method like `setStorageAt`, we should use the full 256 bit word and not a quantity like we're doing. But I think `getStorageAt` uses a quantity, and it makes sense to be consistent with that method here.
