### ISSUE TITLE
Error: Cannot find module '@ethersproject/transactions' when deploy the deploy.js file

### ISSUE THREAD

**Issue by sniper365** [nomiclabs/hardhat#1519] opened 2021-06-08 14:29 UTC
Default Greeter.sol
```
//SPDX-License-Identifier: Unlicense
pragma solidity =0.7.0;

import "hardhat/console.sol";


contract Greeter {
  string greeting;

  constructor(string memory _greeting) {
    console.log("Deploying a Greeter with greeting:", _greeting);
    greeting = _greeting;
  }

  function greet() public view returns (string memory) {
    return greeting;
  }

  function setGreeting(string memory _greeting) public {
    console.log("Changing greeting from '%s' to '%s'", greeting, _greeting);
    greeting = _greeting;
  }
}
```
Default deploy.js
```
// We require the Hardhat Runtime Environment explicitly here. This is optional 
// but useful for running the script in a standalone fashion through `node <script>`.
//
// When running the script with `hardhat run <script>` you'll find the Hardhat
// Runtime Environment's members available in the global scope.
const hre = require("hardhat");

async function main() {
  // Hardhat always runs the compile task when running scripts with its command
  // line interface.
  //
  // If this script is run directly using `node` you may want to call compile 
  // manually to make sure everything is compiled
  // await hre.run('compile');

  // We get the contract to deploy
  const Greeter = await hre.ethers.getContractFactory("Greeter");
  const greeter = await Greeter.deploy("Hello, Hardhat!");

  await greeter.deployed();

  console.log("Greeter deployed to:", greeter.address);
}

// We recommend this pattern to be able to use async/await everywhere
// and properly handle errors.
main()
  .then(() => process.exit(0))
  .catch(error => {
    console.error(error);
    process.exit(1);
  });
```
pacakage.json
```
{
  "name": "pancakeswap-contracts",
  "version": "1.0.0",
  "description": "",
  "main": "hardhat.config.js",
  "devDependencies": {
    "@nomiclabs/hardhat-ethers": "^2.0.2",
    "@nomiclabs/hardhat-waffle": "^2.0.1",
    "@types/chai": "^4.2.18",
    "@types/mocha": "^8.2.2",
    "@types/node": "^15.12.2",
    "chai": "^4.3.4",
    "ethereum-waffle": "^3.3.0",
    "ethers": "^5.3.0",
    "hardhat": "^2.3.0",
    "rimraf": "^3.0.2",
    "ts-node": "^10.0.0",
    "typescript": "^4.3.2"
  },
  "scripts": {
    "clean": "rimraf ./artifacts/",
    "precompile": "yarn clean",
    "compile": "npx hardhat compile",
    "start:server": "npx hardhat node",
    "deploy": "npx hardhat run --network localhost scripts/deploy.js"
  },
  "keywords": [],
  "author": "sniper365",
  "license": "ISC",
  "dependencies": {
    "@pancakeswap/pancake-swap-lib": "^0.0.4",  // those modules aren't used
    "@uniswap/lib": "^4.0.1-alpha",
    "@uniswap/v2-core": "^1.0.1"
  }
}
```
When I run `yarn compile`, all is successful, but when run `yarn deploy` after run `yarn start:server`, I got this error. 
But @ethersproject/transactions module is existed now. anyway I inserted the `"@ethersproject/transactions": "^5.3.0"` in the pacakage.json, but same error. I don't know the reason.

Error
```
$ yarn deploy
yarn run v1.22.5
$ npx hardhat run --network localhost scripts/deploy.js
Error: Cannot find module '@ethersproject/transactions'
Require stack:
- F:\pancake\pancakeswap-contracts\node_modules\ethers\lib\index.js
- F:\pancake\pancakeswap-contracts\scripts\deploy.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:893:15)
    at Function.Module._load (internal/modules/cjs/loader.js:743:27)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (F:\pancake\pancakeswap-contracts\node_modules\@ethersproject\contracts\src.ts\index.ts:10:1)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
```

**Comment by alcuadrado** [comment] 2021-06-08 20:27
Hey @sniper365,

Thanks for opening this issue. Do you have a repository where we can reproduce it? Thanks

**Comment by sniper365** [comment] 2021-06-09 03:42
Hey, @alcuadrado.

Yeah. I made git repository for reproducing. 

[https://github.com/sniper365/pancakeswap-contracts](https://github.com/sniper365/pancakeswap-contracts)

Thank you.

**Comment by fvictorio** [comment] 2021-06-09 13:25
@sniper365 I can't reproduce this. Which version of node are you using? And yarn?

Try removing the `node_modules` directory and running `yarn` again, and then try to run the script again. Does that fix this?

**Comment by fvictorio** [comment] 2021-06-09 13:27
I'm going to close this because I'm pretty sure it's not a Hardhat issue. Please join our [discord server](https://hardhat.org/discord) if you need more help with this. And, of course, please re-open if you think this is indeed a problem on our side.

**Closed by fvictorio** 2021-06-09 13:27 UTC
Labels: status:needs-more-info
