### ISSUE TITLE
[hardhat-etherscan] Will polygonscan be supported soon?

### ISSUE THREAD

**Issue by shanefontaine** [nomiclabs/hardhat#1727] opened 2021-07-25 05:25 UTC
Are there any plans to support https://polygonscan.com with the `hardat-etherscan` package?

The site appears to act exactly like etherscan, with the same API key format and verification steps. Running the command now with Polygon as the destination gives the following:

```
Error in plugin @nomiclabs/hardhat-etherscan: An etherscan endpoint could not be found for this network. ChainID: 137. The selected network is polygon.

Possible causes are:
  - The selected network (polygon) is wrong.
  - Faulty hardhat network config.
```

**Comment by fvictorio** [comment] 2021-07-26 12:06
@shanefontaine Polygon is supported by `hardhat-etherscan`. Maybe you are not using the latest version?

(Closing this preemptively, but feel free to reply here, or to re-open it if you are sure it's not working with the latest version and can provide reproduction steps. Alternatively, use the `#hardhat-etherscan` channel in [our Discord server](https://hardhat.org/discord).)

**Closed by fvictorio** 2021-07-26 12:06 UTC

**Comment by ericnordelo** [comment] 2021-09-28 14:44
Shouldn't be an option to select a contract when verifying? And also why not add the different API Keys in hardhat-config, why is only accepting etherscanApiKey and not polygonScanApiKey?

**Comment by fvictorio** [comment] 2021-09-30 11:51
> And also why not add the different API Keys in hardhat-config, why is only accepting etherscanApiKey and not polygonScanApiKey?

Polygonscan is powered by Etherscan. This plugin started supporting only "ethereum" etherscan, but since the underlying API is the same, we added support for other networks. I agree that it might be confusing; we might change it in the future, or maybe add support for multiple keys.

**Comment by Weng07** [comment] 2022-03-17 20:46
Did I understand it correctly? You mean to say is, even if I deploy on polygon, I still need to use etherscan APi?

**Comment by fvictorio** [comment] 2022-03-18 12:27
Do you mean the API key? If that's the case: no, etherscan and polygonscan use different keys.

**Comment by Weng07** [comment] 2022-03-18 12:49
Got it, but I got a question. If I launch my contract via Polygon, can I
make a website via vscode using ethers? I watched a YT tutorial, but I
can't figure out how to do what to do since the website I was able to copy
only connects to ethereum.

**Comment by fvictorio** [comment] 2022-03-18 13:23
That's unrelated to this issue, or to Hardhat. Also, this issue tracker is not a support channel.
