### ISSUE TITLE
Mainnet Forking ambiguous error when deploying more than X contracts

### ISSUE THREAD

**Issue by ivanzhelyazkov** [nomiclabs/hardhat#1212] opened 2021-01-30 13:42 UTC
I have created a deployment script which deploys 18 contracts.
The script runs fine on the hardhat network, but when the forking option is activated, it fails with the following error: 

`Error: Transaction failed: revert
    at new TransactionExecutionError (/project/node_modules/hardhat/src/internal/hardhat-network/provider/errors.ts:97:16)
    at HardhatNode._manageErrors (/project/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:969:12)
    at HardhatNode.estimateGas (/project/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:508:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at EthModule._estimateGasAction (/project/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:390:9)
    at HardhatNetworkProvider.request (/project/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:102:18)
    at EthersProviderWrapper.send (/project/node_modules/hardhat-deploy-ethers/src/ethers-provider-wrapper.ts:13:20)`

`Caused by: Error: Transaction failed: revert
    at new TransactionExecutionError (/project/node_modules/hardhat/src/internal/hardhat-network/provider/errors.ts:97:16)
    at HardhatNode._manageErrors (/project/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:969:12)
    at HardhatNode.estimateGas (/project/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:508:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at EthModule._estimateGasAction (/project/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:390:9)
    at HardhatNetworkProvider.request (/project/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:102:18)
    at EthersProviderWrapper.send (/project/node_modules/hardhat-deploy-ethers/src/ethers-provider-wrapper.ts:13:20)`

When commenting out deployed contracts code, I have noticed that whenever I am deploying 12 contracts in total or less (doesn't matter which ones), the scripts runs without error.
Is there a limitation to the amount of contracts to be deployed ?
It seems to be a gas estimation issue, but I've passed the following gas options : 
`blockGasLimit: 0x1fffffffffffff,
  allowUnlimitedContractSize: true`

Which should prevent any gas problems.

**Comment by fvictorio** [comment] 2021-02-01 13:34
That's very strange. I think we'll need some way to reproduce this, could you please share a minimal example that reproduces the problem?

**Comment by shark0der** [comment] 2021-02-01 21:51
@fvictorio might be related to the bug I reported regarding the mnemonic's mainnet activity.
@ivanzhelyazkov can you try changing the mnemonic in your hardhat config to a non-default one and see if this still fails?

**Comment by aaronovz1** [comment] 2021-02-05 20:01
I am seeing the same problem

**Comment by chanhosuh** [comment] 2021-02-07 16:30
This strange bound on the number of allowed contract deployments hints at some kind of nonce error.  If you look at the deployer address on the network you are forking, is the 13th outgoing transaction a contract creation?  If so, then doing a forked net deploy where the 13th transaction is a contract creation will fail due to Hardhat's current behavior of resetting an unlocked address' nonce to 0.

See https://github.com/nomiclabs/hardhat/issues/1231

**Comment by fvictorio** [comment] 2021-02-11 16:24
We'll release a fix for this soon. As @shark0der mentioned, changing the default mnemonic is a temporary workaround.

**Comment by fvictorio** [comment] 2021-02-12 12:52
Fixed in 2.0.1.0. Please re-open if you are still having this issue.

**Closed by fvictorio** 2021-02-12 12:52 UTC
Labels: package:hardhat-core
