### ISSUE TITLE
Wrong contract address on deploy to mumbai polygon testnet

### ISSUE THREAD

**Issue by freitasgouvea** [nomiclabs/hardhat#2215] opened 2022-01-06 14:27 UTC
I was using hardhat with https://github.com/OpenZeppelin/openzeppelin-upgrades in poligon testnet mumbai and found a bug related to deployProxy on this network.

What happens is that when we run the deployProxy function on the mumbai network and the transaction that is executed returns with the wrong created contract address.

The repository we used to reproduce this error was https://github.com/jeffprestes/test-proxy-contract

The network is configured with this params in the hardhat config networks:

`        mumbai: {
            url: 'https://rpc-mumbai.maticvigil.com',
            accounts: { mnemonic: mnemonic },
            timeout: 40000,
        },`

And the executed script was:

`
// scripts/deploy.js
async function main () {
  const Box = await ethers.getContractFactory('Box');
  console.log('Deploying Box...');
  console.log(Box);
  const box = await Box.deploy();
  await box.deployed();
  console.log('Box deployed:', box);
  console.log('Box tx hash to:', box.deployTransaction.hash);
  console.log('Box deployed to:', box.address);
}

main()
  .then(() => process.exit(0))
  .catch(error => {
    console.error(error);
    process.exit(1);
  });
`

When we executed this script with the rinkeby testnet and polygon mainnet networks it returned correctly, but with the mumbai network is having this problem.

Below are the deployProxy logs.

On the rinkeby network:

`Box deployed: Contract {
  interface: Interface {
    fragments: [ [EventFragment], [FunctionFragment], [FunctionFragment] ],
    _abiCoder: AbiCoder { coerceFunc: null },
    functions: {
      'retrieve()': [FunctionFragment],
      'store(uint256)': [FunctionFragment]
    },
    errors: {},
    events: { 'ValueChanged(uint256)': [EventFragment] },
    structs: {},
    deploy: ConstructorFragment {
      name: null,
      type: 'constructor',
      inputs: [],
      payable: false,
      stateMutability: 'nonpayable',
      gas: null,
      _isFragment: true
    },
    _isInterface: true
  },
  provider: EthersProviderWrapper {
    _isProvider: true,
    _events: [],
    _emitted: {
      block: 9944335,
      't:0x944371de05eba13ccb57dacaca1d6664f50bfcad9fb3e0aefc1075d53e6c6d0d': 9944335
    },
    formatter: Formatter { formats: [Object] },
    anyNetwork: false,
    _networkPromise: Promise { [Object] },
    _maxInternalBlockNumber: 9944335,
    _lastBlockNumber: 9944335,
    _pollingInterval: 4000,
    _fastQueryDate: 1641477632902,
    connection: { url: 'http://localhost:8545' },
    _nextId: 42,
    _hardhatProvider: BackwardsCompatibilityProviderAdapter {
      _wrapped: AutomaticGasPriceProvider {
        _wrapped: FixedGasProvider {
          _wrapped: [AutomaticSenderProvider],
          _wrappedProvider: [AutomaticSenderProvider],
          _gasLimit: 10000000
        },
        _wrappedProvider: FixedGasProvider {
          _wrapped: [AutomaticSenderProvider],
          _wrappedProvider: [AutomaticSenderProvider],
          _gasLimit: 10000000
        },
        _nodeSupportsEIP1559: true
      },
      _provider: AutomaticGasPriceProvider {
        _wrapped: FixedGasProvider {
          _wrapped: [AutomaticSenderProvider],
          _wrappedProvider: [AutomaticSenderProvider],
          _gasLimit: 10000000
        },
        _wrappedProvider: FixedGasProvider {
          _wrapped: [AutomaticSenderProvider],
          _wrappedProvider: [AutomaticSenderProvider],
          _gasLimit: 10000000
        },
        _nodeSupportsEIP1559: true
      },
      sendAsync: [Function: bound sendAsync],
      send: [Function: bound send],
      _sendJsonRpcRequest: [Function: bound _sendJsonRpcRequest] AsyncFunction
    },
    _eventLoopCache: { detectNetwork: null },
    _network: {
      name: 'rinkeby',
      chainId: 4,
      ensAddress: '0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e',
      _defaultProvider: [Function]
    },
    _internalBlockNumber: Promise { [Object] },
    _fastBlockNumber: 9944335,
    _fastBlockNumberPromise: Promise { 9944335 },
    _poller: null,
    _bootstrapPoll: null
  },
  signer: SignerWithAddress {
    _isSigner: true,
    address: '0xAB3d4f780BfCaF17bC5B4A19cbBa95357655B036',
    _signer: JsonRpcSigner {
      _isSigner: true,
      provider: [EthersProviderWrapper],
      _address: '0xAB3d4f780BfCaF17bC5B4A19cbBa95357655B036',
      _index: null
    },
    provider: EthersProviderWrapper {
      _isProvider: true,
      _events: [],
      _emitted: [Object],
      formatter: [Formatter],
      anyNetwork: false,
      _networkPromise: [Promise],
      _maxInternalBlockNumber: 9944335,
      _lastBlockNumber: 9944335,
      _pollingInterval: 4000,
      _fastQueryDate: 1641477632902,
      connection: [Object],
      _nextId: 42,
      _hardhatProvider: BackwardsCompatibilityProviderAdapter {
        _wrapped: AutomaticGasPriceProvider {
          _wrapped: FixedGasProvider {
            _wrapped: [AutomaticSenderProvider],
            _wrappedProvider: [AutomaticSenderProvider],
            _gasLimit: 10000000
          },
          _wrappedProvider: FixedGasProvider {
            _wrapped: [AutomaticSenderProvider],
            _wrappedProvider: [AutomaticSenderProvider],
            _gasLimit: 10000000
          },
          _nodeSupportsEIP1559: true
        },
        _provider: AutomaticGasPriceProvider {
          _wrapped: FixedGasProvider {
            _wrapped: [AutomaticSenderProvider],
            _wrappedProvider: [AutomaticSenderProvider],
            _gasLimit: 10000000
          },
          _wrappedProvider: FixedGasProvider {
            _wrapped: [AutomaticSenderProvider],
            _wrappedProvider: [AutomaticSenderProvider],
            _gasLimit: 10000000
          },
          _nodeSupportsEIP1559: true
        },
        sendAsync: [Function: bound sendAsync],
        send: [Function: bound send],
        _sendJsonRpcRequest: [Function: bound _sendJsonRpcRequest] AsyncFunction
      },
      _eventLoopCache: [Object],
      _network: [Object],
      _internalBlockNumber: [Promise],
      _fastBlockNumber: 9944335,
      _fastBlockNumberPromise: [Promise],
      _poller: null,
      _bootstrapPoll: null
    }
  },
  callStatic: {
    'retrieve()': [Function],
    'store(uint256)': [Function],
    retrieve: [Function],
    store: [Function]
  },
  estimateGas: {
    'retrieve()': [Function],
    'store(uint256)': [Function],
    retrieve: [Function],
    store: [Function]
  },
  functions: {
    'retrieve()': [Function],
    'store(uint256)': [Function],
    retrieve: [Function],
    store: [Function]
  },
  populateTransaction: {
    'retrieve()': [Function],
    'store(uint256)': [Function],
    retrieve: [Function],
    store: [Function]
  },
  filters: { 'ValueChanged(uint256)': [Function], ValueChanged: [Function] },
  _runningEvents: {},
  _wrappedEmits: {},
  address: '0xB0c3C4Ec201c11985F8b1FF676e2e91E200f7Ea7',
  resolvedAddress: Promise { '0xB0c3C4Ec201c11985F8b1FF676e2e91E200f7Ea7' },
  'retrieve()': [Function],
  'store(uint256)': [Function],
  retrieve: [Function],
  store: [Function],
  deployTransaction: {
    hash: '0x944371de05eba13ccb57dacaca1d6664f50bfcad9fb3e0aefc1075d53e6c6d0d',
    type: 2,
    accessList: [],
    blockHash: null,
    blockNumber: null,
    transactionIndex: null,
    confirmations: 0,
    from: '0xAB3d4f780BfCaF17bC5B4A19cbBa95357655B036',
    gasPrice: BigNumber { value: "2350000005" },
    maxPriorityFeePerGas: BigNumber { value: "2349999975" },
    maxFeePerGas: BigNumber { value: "2350000005" },
    gasLimit: BigNumber { value: "137593" },
    to: null,
    value: BigNumber { value: "0" },
    nonce: 81,
    data: '0x608060405234801561001057600080fd5b50610187806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80632e64cec11461003b5780636057361d14610059575b600080fd5b610043610075565b60405161005091906100d8565b60405180910390f35b610073600480360381019061006e9190610124565b61007e565b005b60008054905090565b806000819055507f93fe6d397c74fdf1402a8b72e47b68512f0510d7b98a4bc4cbdf6ac7108b3c59816040516100b491906100d8565b60405180910390a150565b6000819050919050565b6100d2816100bf565b82525050565b60006020820190506100ed60008301846100c9565b92915050565b600080fd5b610101816100bf565b811461010c57600080fd5b50565b60008135905061011e816100f8565b92915050565b60006020828403121561013a576101396100f3565b5b60006101488482850161010f565b9150509291505056fea26469706673582212201761a6d262cc308d54c436a53715da1d5196475a6b541bcd49001254f9b20b0f64736f6c63430008090033',
    r: '0x66a05326c4b5503e2e0e4ddbf562e1bae52a95c24991f621976c8c177c495023',
    s: '0x3349d98f2c6f5cce6b245562c95a91cb95e1cb1ec0e5f32a18c9a0e480714ab0',
    v: 1,
    creates: '0xB0c3C4Ec201c11985F8b1FF676e2e91E200f7Ea7',
    chainId: 4,
    wait: [Function]
  },
  _deployedPromise: Promise { [Circular] }
}
Box tx hash to: 0x944371de05eba13ccb57dacaca1d6664f50bfcad9fb3e0aefc1075d53e6c6d0d
Box deployed to: 0xB0c3C4Ec201c11985F8b1FF676e2e91E200f7Ea7`

In this case the tx https://rinkeby.etherscan.io/tx/0x944371de05eba13ccb57dacaca1d6664f50bfcad9fb3e0aefc1075d53e6c6d0d created this contract https://rinkeby.etherscan.io/address/0xb0c3c4ec201c11985f8b1ff676e2e91e200f7ea7 and script retuns the correct address.

But on the mumbai network we have this log:

`Box deployed: Contract {
  interface: Interface {
    fragments: [ [EventFragment], [FunctionFragment], [FunctionFragment] ],
    _abiCoder: AbiCoder { coerceFunc: null },
    functions: {
      'retrieve()': [FunctionFragment],
      'store(uint256)': [FunctionFragment]
    },
    errors: {},
    events: { 'ValueChanged(uint256)': [EventFragment] },
    structs: {},
    deploy: ConstructorFragment {
      name: null,
      type: 'constructor',
      inputs: [],
      payable: false,
      stateMutability: 'nonpayable',
      gas: null,
      _isFragment: true
    },
    _isInterface: true
  },
  provider: EthersProviderWrapper {
    _isProvider: true,
    _events: [],
    _emitted: {
      block: 23602264,
      't:0x1964b7f3ec2e33e551092d39e6a336233edadcda1d6f7f6905b34b28c3175c18': 23602265
    },
    formatter: Formatter { formats: [Object] },
    anyNetwork: false,
    _networkPromise: Promise { [Object] },
    _maxInternalBlockNumber: 23602264,
    _lastBlockNumber: 23602264,
    _pollingInterval: 4000,
    _fastQueryDate: 1641477725983,
    connection: { url: 'http://localhost:8545' },
    _nextId: 42,
    _hardhatProvider: BackwardsCompatibilityProviderAdapter {
      _wrapped: AutomaticGasPriceProvider {
        _wrapped: AutomaticGasProvider {
          _wrapped: [AutomaticSenderProvider],
          _wrappedProvider: [AutomaticSenderProvider],
          _gasMultiplier: 1
        },
        _wrappedProvider: AutomaticGasProvider {
          _wrapped: [AutomaticSenderProvider],
          _wrappedProvider: [AutomaticSenderProvider],
          _gasMultiplier: 1
        },
        _nodeSupportsEIP1559: true
      },
      _provider: AutomaticGasPriceProvider {
        _wrapped: AutomaticGasProvider {
          _wrapped: [AutomaticSenderProvider],
          _wrappedProvider: [AutomaticSenderProvider],
          _gasMultiplier: 1
        },
        _wrappedProvider: AutomaticGasProvider {
          _wrapped: [AutomaticSenderProvider],
          _wrappedProvider: [AutomaticSenderProvider],
          _gasMultiplier: 1
        },
        _nodeSupportsEIP1559: true
      },
      sendAsync: [Function: bound sendAsync],
      send: [Function: bound send],
      _sendJsonRpcRequest: [Function: bound _sendJsonRpcRequest] AsyncFunction
    },
    _eventLoopCache: { detectNetwork: null },
    _network: {
      name: 'maticmum',
      chainId: 80001,
      ensAddress: null,
      _defaultProvider: null
    },
    _internalBlockNumber: Promise { [Object] },
    _fastBlockNumber: 23602264,
    _fastBlockNumberPromise: Promise { 23602264 },
    _poller: null,
    _bootstrapPoll: null
  },
  signer: SignerWithAddress {
    _isSigner: true,
    address: '0xAB3d4f780BfCaF17bC5B4A19cbBa95357655B036',
    _signer: JsonRpcSigner {
      _isSigner: true,
      provider: [EthersProviderWrapper],
      _address: '0xAB3d4f780BfCaF17bC5B4A19cbBa95357655B036',
      _index: null
    },
    provider: EthersProviderWrapper {
      _isProvider: true,
      _events: [],
      _emitted: [Object],
      formatter: [Formatter],
      anyNetwork: false,
      _networkPromise: [Promise],
      _maxInternalBlockNumber: 23602264,
      _lastBlockNumber: 23602264,
      _pollingInterval: 4000,
      _fastQueryDate: 1641477725983,
      connection: [Object],
      _nextId: 42,
      _hardhatProvider: BackwardsCompatibilityProviderAdapter {
        _wrapped: AutomaticGasPriceProvider {
          _wrapped: AutomaticGasProvider {
            _wrapped: [AutomaticSenderProvider],
            _wrappedProvider: [AutomaticSenderProvider],
            _gasMultiplier: 1
          },
          _wrappedProvider: AutomaticGasProvider {
            _wrapped: [AutomaticSenderProvider],
            _wrappedProvider: [AutomaticSenderProvider],
            _gasMultiplier: 1
          },
          _nodeSupportsEIP1559: true
        },
        _provider: AutomaticGasPriceProvider {
          _wrapped: AutomaticGasProvider {
            _wrapped: [AutomaticSenderProvider],
            _wrappedProvider: [AutomaticSenderProvider],
            _gasMultiplier: 1
          },
          _wrappedProvider: AutomaticGasProvider {
            _wrapped: [AutomaticSenderProvider],
            _wrappedProvider: [AutomaticSenderProvider],
            _gasMultiplier: 1
          },
          _nodeSupportsEIP1559: true
        },
        sendAsync: [Function: bound sendAsync],
        send: [Function: bound send],
        _sendJsonRpcRequest: [Function: bound _sendJsonRpcRequest] AsyncFunction
      },
      _eventLoopCache: [Object],
      _network: [Object],
      _internalBlockNumber: [Promise],
      _fastBlockNumber: 23602264,
      _fastBlockNumberPromise: [Promise],
      _poller: null,
      _bootstrapPoll: null
    }
  },
  callStatic: {
    'retrieve()': [Function],
    'store(uint256)': [Function],
    retrieve: [Function],
    store: [Function]
  },
  estimateGas: {
    'retrieve()': [Function],
    'store(uint256)': [Function],
    retrieve: [Function],
    store: [Function]
  },
  functions: {
    'retrieve()': [Function],
    'store(uint256)': [Function],
    retrieve: [Function],
    store: [Function]
  },
  populateTransaction: {
    'retrieve()': [Function],
    'store(uint256)': [Function],
    retrieve: [Function],
    store: [Function]
  },
  filters: { 'ValueChanged(uint256)': [Function], ValueChanged: [Function] },
  _runningEvents: {},
  _wrappedEmits: {},
  address: '0xCc64e1fFC33D7B99013AAb5D71E34886310040a0',
  resolvedAddress: Promise { '0xCc64e1fFC33D7B99013AAb5D71E34886310040a0' },
  'retrieve()': [Function],
  'store(uint256)': [Function],
  retrieve: [Function],
  store: [Function],
  deployTransaction: {
    hash: '0x1964b7f3ec2e33e551092d39e6a336233edadcda1d6f7f6905b34b28c3175c18',
    type: 2,
    accessList: [],
    blockHash: null,
    blockNumber: null,
    transactionIndex: null,
    confirmations: 0,
    from: '0x0000000000000000000000000000000000000000',
    gasPrice: BigNumber { value: "2000000001" },
    maxPriorityFeePerGas: BigNumber { value: "1999999991" },
    maxFeePerGas: BigNumber { value: "2000000001" },
    gasLimit: BigNumber { value: "137593" },
    to: null,
    value: BigNumber { value: "0" },
    nonce: 13,
    data: '0x608060405234801561001057600080fd5b50610187806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80632e64cec11461003b5780636057361d14610059575b600080fd5b610043610075565b60405161005091906100d8565b60405180910390f35b610073600480360381019061006e9190610124565b61007e565b005b60008054905090565b806000819055507f93fe6d397c74fdf1402a8b72e47b68512f0510d7b98a4bc4cbdf6ac7108b3c59816040516100b491906100d8565b60405180910390a150565b6000819050919050565b6100d2816100bf565b82525050565b60006020820190506100ed60008301846100c9565b92915050565b600080fd5b610101816100bf565b811461010c57600080fd5b50565b60008135905061011e816100f8565b92915050565b60006020828403121561013a576101396100f3565b5b60006101488482850161010f565b9150509291505056fea26469706673582212201761a6d262cc308d54c436a53715da1d5196475a6b541bcd49001254f9b20b0f64736f6c63430008090033',
    r: '0x0c052aa29fd541531d68591c39c8582939e86f16d8ac48b4b030dc5de4600453',
    s: '0x30e766f6e9defac859033714b55cf427c893b6d3c5d7c9a10157230b17c9eada',
    v: 0,
    creates: '0xCc64e1fFC33D7B99013AAb5D71E34886310040a0',
    chainId: 80001,
    wait: [Function]
  },
  _deployedPromise: Promise { [Circular] }
}
Box tx hash to: 0x1964b7f3ec2e33e551092d39e6a336233edadcda1d6f7f6905b34b28c3175c18
Box deployed to: 0xCc64e1fFC33D7B99013AAb5D71E34886310040a0`

And in this case the tx https://mumbai.polygonscan.com/tx/0x1964b7f3ec2e33e551092d39e6a336233edadcda1d6f7f6905b34b28c3175c18 created this contract https://mumbai.polygonscan.com/address/0xa058aef62e9c94e49821310694f3c83e2f82cfdf but the script retuns incorrect contract address 0xCc64e1fFC33D7B99013AAb5D71E34886310040a0.

 I don't know if this error is related to ethersjs.

**Comment by freitasgouvea** [comment] 2022-01-06 14:47
I found this same issue here https://github.com/nomiclabs/hardhat/issues/2162

**Comment by alcuadrado** [comment] 2022-01-06 14:54
Hey @freitasgouvea, this is in fact a duplicate of #2162. Using Alchemy workarounds the problem.

**Closed by alcuadrado** 2022-01-06 14:54 UTC
