### ISSUE TITLE
HH606 Error: Truffle can compile with the same settings.

### ISSUE THREAD

**Issue by NotLuksus** [nomiclabs/hardhat#1817] opened 2021-08-22 18:50 UTC
So currently I'm working on an ERC721 Contract based of OpenZeppelins implementation.
The implementation lives in a file called ERC721.sol and this file by its own compiles without any problems.
The moment I try to import it into another file and try to compile it. It crashes.
Exception is:
Error HH606: The project cannot be compiled, see reasons below.

These files and its dependencies cannot be compiled with your config. This can happen because they have incompatible Solidity pragmas, or don't match any of your configured Solidity compilers.

  * contracts/Contract.sol

To learn more, run the command again with --verbose

Read about compiler configuration at https://hardhat.org/config

For more info go to https://hardhat.org/HH606 or run Hardhat with --show-stack-traces

The pragma statements are the same everywhere.

Truffle is able to compile it without any issues.

Thank you for your help!

**Comment by fvictorio** [comment] 2021-08-25 16:24
As the error message says, when you import a dependency you can end up with something that cannot be compiled. For example, you might be using solc 0.8.3 and this contract, and that will compile fine:

```solidity
pragma solidity ^0.8.0

contract Foo {}
```

But if you then import some file that uses `0.8.2` (without the `^`), then the file will not be compilable.

That's just an example, the specific reason here depends a lot on what you're doing.

I'm closing this since I'm pretty sure it's expected behavior. 
Please use [our Discord server](https://hardhat.org/discord) if you have further questions.

**Closed by fvictorio** 2021-08-25 16:24 UTC
