### ISSUE TITLE
Node Locks - HardhatError: HH109: Network connection timed out.

### ISSUE THREAD

**Issue by aliveli186** [nomiclabs/hardhat#2381] opened 2022-02-13 22:36 UTC
Can not deploy to localhost node.

Started HTTP and WebSocket JSON-RPC server at http://127.0.0.1:8545/

**Deployment script fires this error:**
```
HardhatError: HH109: Network connection timed out.
Please check your internet connection and networks config
    at HttpProvider._fetchJsonRpcResponse (G:\Blockchain\project1\node_modules\hardhat\src\internal\core\providers\http.ts:184:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
    at HttpProvider.request (G:\Blockchain\project1\node_modules\hardhat\src\internal\core\providers\http.ts:55:29)
    at GanacheGasMultiplierProvider._isGanache (G:\Blockchain\project1\node_modules\hardhat\src\internal\core\providers\gas-providers.ts:317:30)
    at GanacheGasMultiplierProvider.request (G:\Blockchain\project1\node_modules\hardhat\src\internal\core\providers\gas-providers.ts:306:23)
    at EthersProviderWrapper.send (G:\Blockchain\project1\node_modules\@nomiclabs\hardhat-ethers\src\internal\ethers-provider-wrapper.ts:13:20)
    at getSigners (G:\Blockchain\project1\node_modules\@nomiclabs\hardhat-ethers\src\internal\helpers.ts:45:20)

    Caused by: FetchError: network timeout at: http://127.0.0.1:8545/
        at Timeout.<anonymous> (G:\Blockchain\project1\node_modules\node-fetch\lib\index.js:1484:13)
        at listOnTimeout (node:internal/timers:559:17)
        at processTimers (node:internal/timers:502:7)
```

**hardhat.config.js**
```
module.exports = {
  solidity: {
    version: "0.8.11",
    settings: {
      optimizer: {
        enabled: true,
        runs: 200,
      }
    }
  },
  networks: {
    localhost: {
      url: "http://127.0.0.1:8545"
    }
  }
}
```

**package.json**
```
  "devDependencies": {
    "@nomiclabs/hardhat-ethers": "^2.0.5",
    "@nomiclabs/hardhat-waffle": "^2.0.2",
    "chai": "^4.3.6",
    "ethereum-waffle": "^3.4.0"
  },
  "dependencies": {
    "@openzeppelin/contracts": "^4.5.0",
    "@primitivefi/hardhat-dodoc": "^0.1.3",
    "@uniswap/v2-periphery": "^1.1.0-beta.0",
    "ethers": "^5.5.4",
    "hardhat": "^2.8.4",
    "hardhat-contract-sizer": "^2.4.0"
  }
```

**Comment by aliveli186** [comment] 2022-02-13 23:53
When I restart the computer and then run the Hardhat node for the the first time I can deploy but as soon as I start the second connection let's say MetaMask it locks the node completely.

**Comment by linyuliang** [comment] 2022-02-14 13:25
try downgrade your metamask to version 10.8.1. It works for me.

**Comment by aliveli186** [comment] 2022-02-14 19:18
> try downgrade your metamask to version 10.8.1. It works for me.

Even if I don't use MetaMask like my deploy script also doesn't connect.

**Comment by feuGeneA** [comment] 2022-02-14 21:50
At first glance, this sounds to me like a different symptom of the same problem that you described in #2380 . Do you have reason to believe there are two different issues?

**Comment by aliveli186** [comment] 2022-02-14 22:48
> At first glance, this sounds to me like a different symptom of the same problem that you described in #2380 . Do you have reason to believe there are two different issues?

Yes, I also think they are the same.

**Comment by feuGeneA** [comment] 2022-02-14 23:15
Closing as a duplicate of #2380 , because the issue described here appears to be a secondary symptom of the problem described there.

**Closed by feuGeneA** 2022-02-14 23:15 UTC
