### ISSUE TITLE
Hardhat fails to notify "Stack too deep" on compilation

### ISSUE THREAD

**Issue by drbullock** [nomiclabs/hardhat#1070] opened 2020-11-30 09:46 UTC
I was trying to debug a contract because it failed compilation. In the beginning, I opened a ticket in [OpenZeppelin](https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/246), but after debugging in Remix, I found that the issue is with "Stack too Deep", but I didn't have any warning in VScode, nor in Hardhat compilation.

**Comment by fvictorio** [comment] 2020-11-30 15:37
Hi @drbullock, can you share some reproduction steps?

**Comment by fvictorio** [comment] 2020-12-22 12:03
Closing this since we don't have enough information to look into it, but feel free to re-open if you can provide that info.

**Comment by drbullock** [comment] 2020-12-24 13:56
Hi @fvictorio finally it occurred again and added a Test Repo for that: https://github.com/drbullock/Z05T2, the stack too deep happens in `ReserveModule.freezeUserLiquidityETH()`. I get this error when trying to compile:

```

$ npx hardhat compile
(node:22240) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22240) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
Compiling 12 files with 0.7.5
An unexpected error occurred:

TypeError: Cannot read property 'object' of undefined
    at Object.validate (C:\wamp64\www\TOKEN\Z05T2\node_modules\@openzeppelin\upgrades-core\src\validate.ts:79:32)
    at OverriddenTaskDefinition._action (C:\wamp64\www\TOKEN\Z05T2\node_modules\@openzeppelin\hardhat-upgrades\src\index.ts:19:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Environment._runTaskDefinition (C:\wamp64\www\TOKEN\Z05T2\node_modules\hardhat\src\internal\core\runtime-environment.ts:217:14)       
    at Environment.run (C:\wamp64\www\TOKEN\Z05T2\node_modules\hardhat\src\internal\core\runtime-environment.ts:130:14)
    at SimpleTaskDefinition.action (C:\wamp64\www\TOKEN\Z05T2\node_modules\hardhat\src\builtin-tasks\compile.ts:964:37)
    at Environment._runTaskDefinition (C:\wamp64\www\TOKEN\Z05T2\node_modules\hardhat\src\internal\core\runtime-environment.ts:217:14)       
    at Environment.run (C:\wamp64\www\TOKEN\Z05T2\node_modules\hardhat\src\internal\core\runtime-environment.ts:130:14)
    at SimpleTaskDefinition.action (C:\wamp64\www\TOKEN\Z05T2\node_modules\hardhat\src\builtin-tasks\compile.ts:395:45)
    at Environment._runTaskDefinition (C:\wamp64\www\TOKEN\Z05T2\node_modules\hardhat\src\internal\core\runtime-environment.ts:217:14)       

```

**Comment by fvictorio** [comment] 2020-12-24 16:05
Thank you @drbullock, reopening.

**Comment by frangio** [comment] 2020-12-24 16:13
This may be an instance of https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/250. It was fixed a few weeks ago.

@drbullock Can you try updating @openzeppelin/hardhat-upgrades and @openzeppelin/upgrades-core to their latest versions?

**Comment by drbullock** [comment] 2020-12-28 09:02
@frangio looks like that, I will test today, Thank You!

**Comment by fvictorio** [comment] 2021-01-05 17:27
@drbullock did you have a chance to test that?

**Comment by drbullock** [comment] 2021-01-06 11:26
@fvictorio it works fine, thank you, and sorry for the delay. You can close this

**Closed** 2021-01-06 13:53 UTC
Labels: status:needs-research
