### ISSUE TITLE
Hardhat forking cronos testnet issue:HardhatError: HH110: Invalid JSON-RPC response received: Request exceeds payload size limit(500000)  or batch object limit(1). 

### ISSUE THREAD

**Issue by namhoiyee** [nomiclabs/hardhat#2111] opened 2021-11-29 04:46 UTC
I tried to fork cronos testnet on hardhat and when I run the script I got this error:
HardhatError: HH110: Invalid JSON-RPC response received: Request exceeds payload size limit(500000)  or batch object limit(1). Payload: 360 Batch Object Count: 3

Here is my hardhat config:
`hardhat: {
      chainId: 338,
      forking: {
        url: "https://cronos-testnet-3.crypto.org:8545/",
      },`

Here's is the script im trying to run:
`const MockERC20Factory = (await ethers.getContractFactory(
            "MockERC20",
            deployer
        ));
const tokenA = await MockERC20Factory.deploy();`

If I run it on testnet without forking, it works. But when I try to fork it, it does not work. Any insights on how to fix this?

**Comment by fvictorio** [comment] 2021-11-29 11:46
This seems a problem with the node you're using. If they have a payload limit that most other nodes don't have, there isn't much we can do.

Closing this for now, but feel free to re-open if you're sure the problem is on our side.

**Closed by fvictorio** 2021-11-29 11:46 UTC

**Comment by lwightmoon** [comment] 2021-12-22 09:29
how to change the object limit

**Comment by chrisCryptoCom** [comment] 2022-02-14 07:32
If you need a work around you can:

1. Run a local fork with ganache (which seems not to use `batchRequest`) at different port: `ganache-cli --fork https://evm-cronos.crypto.org --port 8546`
2. Run hardhat fork from your local ganache fork (setting  `forking: { url: "http://localhost:8546" }`

**Comment by nhynhyiddy** [comment] 2022-02-14 07:39
@chrisCryptoCom this defeats the purpose of hardhat since ganache forking doesnt support hardhat's console.sol.

**Comment by chrisCryptoCom** [comment] 2022-05-04 09:19
@nhynhyiddy Since you will be running your tests against the hardhat node, console.sol should work

**Comment by Jenesyx** [comment] 2022-06-11 09:41
My code is like
```
module.exports = {
  solidity: "0.8.4",
  networks: {
    mumbai: {
      url: "https://rpc-mumbai.maticvigil.com",
      accounts: ["my key"]
    }
  }
};
```
and I got "HardhatError: HH110: Invalid JSON-RPC response received: error code: 1020" error
