### ISSUE TITLE
hardhat-network eth_getStorageAt() returns `0x0`, incompatible with ethers getStorageAt()

### ISSUE THREAD

**Issue by pyggie** [nomiclabs/hardhat#987] opened 2020-11-04 05:05 UTC
When using the Hardhat network EVM, if I call `hre.ethers.provider.getStorageAt(addr, key)` and the storage location is empty (zero), then Hardhat network EVM responds to the `eth_getStorageAt` JSON-RPC request with `0x0`, and then ethers throws an error in hexlify() trying to interpret this, saying it needs an even number of hex digits.

The hexlify() call:
https://github.com/ethers-io/ethers.js/blob/e0b1d0e1e0280af860aaa593744a1a177f828397/packages/providers/src.ts/base-provider.ts#L973

The error doesn't happen with ganache or geth. In both cases, the `eth_getStorageAt` JSON-RPC request responds with `0x0000000000000000000000000000000000000000000000000000000000000000`.

**Comment by pyggie** [comment] 2020-11-04 05:16
The stack trace:
```

     Error: hex data is odd-length (argument="value", value="0x0", code=INVALID_ARGUMENT, version=bytes/5.0.5)
      at Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:205:28)
      at Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:217:20)
      at Logger.throwArgumentError (node_modules/@ethersproject/logger/src.ts/index.ts:221:21)
      at hexlify (node_modules/@ethersproject/bytes/src.ts/index.ts:227:24)
      at EthersProviderWrapper.<anonymous> (node_modules/@ethersproject/providers/src.ts/base-provider.ts:973:16)
      ...
```

**Comment by wighawag** [comment] 2020-11-04 22:33
this is a duplicate of : https://github.com/nomiclabs/hardhat/issues/978 (I should have added getStorageAt in the title :)

Interesting that geth/ganache return that value. I was expecting it should return `0x`

**Comment by alcuadrado** [comment] 2020-11-05 15:03
This is a bug. Thanks for reporting it, @pyggie! `eth_getStorageAt` should always return 32 bytes.

**Closed** 2020-11-09 15:25 UTC
Labels: type:bug
