### ISSUE TITLE
_signTypedData() not exposed on SignerWithAddress

### ISSUE THREAD

**Issue by thegostep** [nomiclabs/hardhat#1197] opened 2021-01-24 19:25 UTC
_signTypedData() not exposed on SignerWithAddress.

```
const accounts = await ethers.getSigners()
accounts[0]._signTypedData()
```

**Comment by scnale** [comment] 2021-01-25 16:15
I think this is a duplicate of #1108. Note that there's a workaround like this:
```js
const signer = ethers.provider.getSigner(0);
await signer._signTypedData(...args);
```

**Closed by scnale** 2021-01-25 16:15 UTC
