### ISSUE TITLE
Custom contract error does not contain decoded error messages

### ISSUE THREAD

**Issue by makoto** [nomiclabs/hardhat#1882] opened 2021-09-15 11:14 UTC
Solidity

```
//SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.7;
contract Greeter {
    string private greeting;
    constructor(string memory _greeting) {
        greeting = _greeting;
    }
    error GreetError(string msg);
    function greet() public view returns (string memory) {
      revert GreetError(greeting);
    }
}
```

Test

```
const { ethers } = require("hardhat");

describe("Greeter", function () {
  it("Should return the new greeting once it's changed", async function () {
    const Greeter = await ethers.getContractFactory("Greeter");
    const greeter = await Greeter.deploy("Hello, world!");
    await greeter.deployed();    
    try{
      await greeter.greet();
    }catch(e){
      console.log(e.message)
      console.log(Object.keys(e));
    }
  });
});
```

The test result

```
$npx hardhat test


  Greeter
VM Exception while processing transaction: reverted with custom error 'GreetError("Hello, world!")'
[ 'stackTrace' ]
    ✓ Should return the new greeting once it's changed (1922ms)


  1 passing (2s)
```

According to https://blog.ricmoo.com/highlights-ethers-js-may-2021-2826e858277d, ethers.js should decode the custom error and should add attributes like `errorName`, `code`, `errorArgs` but the error in the est only has `stackTrace`.

**Comment by paulrberg** [comment] 2021-09-15 11:58
Possible duplicate of #1618.

**Comment by fvictorio** [comment] 2021-09-15 12:30
I don't think it's a duplicate, this is about the metadata you get when you catch an error that is a custom error, if I'm understanding correctly.

**Comment by Arachnid** [comment] 2021-12-13 05:43
With this issue unresolved, it's effectively impossible to automatically handle custom errors in code that relies on Hardhat. If Hardhat knows the ABI of the `Error` object it will print out a handy message, but either way there's no way for a program to catch the revert and read the arguments to the custom error type.

In order to be [compatible with ethers](https://github.com/ethers-io/ethers.js/blob/master/packages/contracts/src.ts/index.ts#L388) and in line with other implementations, it should [return the error data from eth_call as the result](https://github.com/ethers-io/ethers.js/blob/master/packages/abi/src.ts/interface.ts#L403). Alternately it could return the error data as a property on the exception that is thrown, which would be incompatible with the RPC interface of other nodes, but at least make catching and interpreting revert reasons *possible*.

What can we do to get this fixed/implemented? Would posting a bounty be useful?

**Comment by Arachnid** [comment] 2021-12-13 07:28
In the meantime, anyone looking for a workaround can try this:
```
//SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

contract RevertProxy {
    function call(address payable target, bytes calldata data) external payable returns(bytes memory) {
        (, bytes memory response) = target.call{value:msg.value}(data);
        return response;
    }
}
```

Deploy that to your hardhat node and make calls via it, and any reverts will be turned into returns, and handled by Ethers etc as expected.

**Comment by alcuadrado** [comment] 2021-12-14 15:49
Hey @Arachnid, @makoto 

> In order to be compatible with ethers and in line with other implementations, it should return the error data from eth_call as the result. 

You can enable this behavior by setting `networks.hardhat.throwOnCallFailures` to `false` in your config. There's also `networks.hardhat.throwOnTransactionFailures`. When building Hardhat Network we decided to copy Ganache's non-standard behavior for compatibility reasons but added these options to let users opt-in into a more standard behavior.

Would this work for you?

> Alternately it could return the error data as a property on the exception that is thrown, which would be incompatible with the RPC interface of other nodes, but at least make catching and interpreting revert reasons possible.

I think we should provide this info when `throwOnCallFailures` or `throwOnTransactionFailures` are enabled. This would not be standard, but unfortunately, we have already deviated from the standard. The main open question would be how to decode the arguments. We can't use ether's types inside hardhat network.

**Comment by Arachnid** [comment] 2021-12-14 23:36
> You can enable this behavior by setting networks.hardhat.throwOnCallFailures to false in your config. There's also networks.hardhat.throwOnTransactionFailures. When building Hardhat Network we decided to copy Ganache's non-standard behavior for compatibility reasons but added these options to let users opt-in into a more standard behavior.

This is true - but it means that you can't recover error data at all if these options are on. What you suggest later would make the most sense. If you include the raw revert data, Ethers can add support for decoding it easily.

**Comment by alcuadrado** [comment] 2021-12-16 14:22
@Arachnid, to make sure I understand: do you mean adding the raw returndata to our custom `SolidityError` exception type? That sounds reasonable

**Comment by Arachnid** [comment] 2021-12-16 19:56
Yup, that's what I had in mind.

**Comment by alcuadrado** [comment] 2022-01-03 20:39
I'm closing this issue in favor of #2211. Thanks everyone for your input!

**Closed by alcuadrado** 2022-01-03 20:39 UTC
Labels: status:needs-research, package:hardhat-core
