### ISSUE TITLE
Gas usage does not match that of mainnet

### ISSUE THREAD

**Issue by ItsNickBarry** [nomiclabs/hardhat#990] opened 2020-11-04 22:16 UTC
See the linked repository for reproduction steps.

The test here indicates that the gas usage for the `AirdropToken#airdrop` function uses about 5 million gas for the given inputs:
https://github.com/jusdefi/jusdefi/blob/2c32d238559773e9b5007da3981502812189909d/test/airdrop_token.js#L106

The same estimate is returned on both Hardhat Network and Ganache.

The script here would not run because the estimated gas requirement, for the same inputs:
https://github.com/jusdefi/jusdefi/blob/master/scripts/airdrop.js

Reducing the size of the inputs (`require('airdrop-ledger/airdrops.json').slice(0, 130)`) yields a gas estimate of about 1.5 million.  However, the mainnet transaction cost about 3.3 million: https://etherscan.io/tx/0x11f1950bf18553a7d39e13cd117b3958946507f3d622e7b0981e6ac36ca70a65

The same transaction on RInkeby also used about 3.3 million gas: https://rinkeby.etherscan.io/tx/0x6759621ab32fd7e0925f5e654a8b54e2c53022a9d4a8574a7227c8e5a3218da5

**Comment by gitpusha** [comment] 2020-11-20 05:14
Hi, 

I observed similar disrepancies and I reported them here in `hardhat-gas-reporter` 

https://github.com/cgewecke/hardhat-gas-reporter/issues/46#issuecomment-730435895

**Comment by ItsNickBarry** [comment] 2020-11-20 07:19
@gitpusha I don't think it's a gas reporter issue because the `gasUsed` in the transaction receipt matches the gas report.

**Comment by fvictorio** [comment] 2020-11-20 19:26
Thanks for this @ItsNickBarry. I opened #1043, which is like a simplified version of this. I'll keep this one open though, in case fixing that one doesn't fix it for you.

**Comment by gitpusha** [comment] 2020-11-23 06:47
> @gitpusha I don't think it's a gas reporter issue because the `gasUsed` in the transaction receipt matches the gas report.

Yes, indeed. It seems to be a hardhat network issue.

**Comment by gitpusha** [comment] 2020-11-29 15:15
I am still observing about 10% and more higher gasUsed values on mainnet when comparing it to what I observe on hardhat network in forking mode.

**Comment by alcuadrado** [comment] 2020-11-29 20:19
Can you tell us how to reproduce it,  @gitpusha ?

**Comment by gitpusha** [comment] 2020-11-30 09:45
Unfortunately, it's very hard to reproduce. You would have to run our integration tests and then execute the transaction on mainnet for comparison. And to be able to execute that transaction you would have to jump through some hoops too.

**Comment by fvictorio** [comment] 2020-11-30 15:23
@gitpusha can you tell us which repository has these tests?

**Comment by gitpusha** [comment] 2020-12-02 16:49
> @gitpusha can you tell us which repository has these tests?

Yep, sorry. Wanted to do that anyway but forget. 

[Here](https://github.com/gelatodigital/gelato-instadapp/tree/master/test/gas/debt_bridge/full/from_maker) are some tests that we run with gas-reporter in order to hardcode gas values. 

We know that for the [execViaRoute0](https://github.com/gelatodigital/gelato-instadapp/blob/039d4b7b3450df5cadf85963f458c992d172573a/test/gas/debt_bridge/full/from_maker/0_ETHA-ETHB.mock.test.js#L129) test 

and for the [execViaRoute0AndOpenVault](https://github.com/gelatodigital/gelato-instadapp/blob/039d4b7b3450df5cadf85963f458c992d172573a/test/gas/debt_bridge/full/from_maker/1_ETHA-newETHB.mock.test.js#L128) test 

the observed gas values on mainnet are like 200k gas higher than the `gasUsed` reported when running them on hardhat network forking mainnet. 

For example this is a [mainnet tx](https://etherscan.io/tx/0x156d258d4fa70f466c781b3ea4021e169372c48a7a4478852646c3de3d32f284) almost identical to the one we gas test in `execViaRoute0` test. 

And it has this gasUsed on mainnet: `2,242,206`

![image](https://user-images.githubusercontent.com/36712489/100903194-e596d080-34c5-11eb-82df-b6a79fbd73ef.png)

while locally the gas reporter tells us the gasUsed is around: `1,969,593`

![image](https://user-images.githubusercontent.com/36712489/100903927-bcc30b00-34c6-11eb-9f81-599442cc7030.png)

**Comment by fvictorio** [comment] 2020-12-03 14:26
Thanks @gitpusha, we'll look into this as soon as possible.

**Comment by fvictorio** [comment] 2020-12-03 15:08
So, I did a first dive into this, and I noticed that the gas cost of that function changes between different executions, _even if the forked block number is the same_. I have no idea how this setup works, but there seems to be some prices that are fetched and/or mocked, and those can change between executions, right?

My point is that if there's already a difference between executions, then it's not entirely off to think that that mainnet tx had a different gas usage because of that. That being said, 200K is not a tiny difference, so I don't dismiss the possibility of a bug on our side. But I don't think we can do much without a more scoped example.

I think the bare mininum we'd need to debug this is to be able to run the same test in the forked mainnet and in non-forked hardhat (or at least on a testnet), and for those two tests to consistently give the same gas usage in each network, but a different value between them.

**Comment by gitpusha** [comment] 2020-12-03 15:57
> I think the bare mininum we'd need to debug this is to be able to run the same test in the forked mainnet and in non-forked hardhat (or at least on a testnet), and for those two tests to consistently give the same gas usage in each network, but a different value between them.

Yes, I agree. Problem is this test uses a lot of dependencies not available on any testnet. 

> I have no idea how this setup works, but there seems to be some prices that are fetched and/or mocked, and those can change between executions, right?

It's a bit hard to go into the details of this test. But the mocked parts are very little and insignificant. We are pretty certain that the gas counting must be off somewhere on hardhat network. 

But without being able to give you a nice example to reproduce it, I don't think it's worth bothering you with it. Unfortunately I cannot distill this down. The integration here is very complex using forked state from many different mainnet protocols (InstaDapp, Maker, DyDx... )

**Comment by jflatow** [comment] 2021-03-24 03:47
I am still seeing an issue that looks a lot like what's described above. These 2 transactions ran out of gas (others went through successfully, but I can't tell when it's going to happen, and I don't want to try again until I know what's wrong) and this is costing me thousands of dollars already :( . I simulated the changes on a mainnet fork before submitting, so this is very upsetting.

https://etherscan.io/tx/0xcf375f7961ea945e0da0fd0703e716e9e13ae54a3f4273dbac0bbba673dd2750
https://etherscan.io/tx/0xa5428ee30e33632db1019bfcc162d99e849c618bb8f60fe2813e37852c786b24

**Comment by fvictorio** [comment] 2021-03-30 14:06
@jflatow simulating a transaction in the mainnet fork is not guaranteed to give you the same gas that will be used when you send the transaction, because some state could've changed in the meantime.

You can use it to get an approximate idea, but then you should probably add a buffer to be sure it will work. Since the unused gas is returned, you don't really lose anything by doing this and you err on the safe side.

**Comment by fvictorio** [comment] 2021-06-10 22:38
Closing this since we don't have an easy way to reproduce the problem. Please re-open if anyone has!

**Closed by fvictorio** 2021-06-10 22:38 UTC
