### ISSUE TITLE
mumbai Test node use upgrades.deployProxy Deployment contract tips No contract at address xxx (Removed from manifest)

### ISSUE THREAD

**Issue by qq335103060** [nomiclabs/hardhat#2182] opened 2021-12-22 08:12 UTC
const Token = await ethers.getContractFactory("token");
  console.log("Deploying Token...");
  const t = await upgrades.deployProxy(Token, { initializer: '__Token_init' });
  await t.deployed();
There is no problem with deployment on other links, error is reported when using mumbai test chain：
`InvalidDeployment [Error]: No contract at address 0x152bbF5657B4d0269378D5aeCC30895b4C6E66E3 (Removed from manifest)
    at waitAndValidateDeployment (./node_modules/@openzeppelin/upgrades-core/src/deployment.ts:92:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at fetchOrDeployGeneric (.//node_modules/@openzeppelin/upgrades-core/src/impl-store.ts:43:5)
    at deployImpl (.//node_modules/@openzeppelin/hardhat-upgrades/src/utils/deploy-impl.ts:60:16)
    at Proxy.deployProxy (.//node_modules/@openzeppelin/hardhat-upgrades/src/deploy-proxy.ts:35:28)
    at main (.//scripts/deploy_upgradeable_token.js:6:19)`

**Comment by kanej** [comment] 2022-01-03 09:51
Closing as a duplicate of https://github.com/nomiclabs/hardhat/issues/2162

**Closed by kanej** 2022-01-03 09:51 UTC
