### ISSUE TITLE
Bug under Windows

### ISSUE THREAD

**Issue by railty** [nomiclabs/hardhat#1460] opened 2021-05-18 00:42 UTC
Under Windows, "npx hardhat help" will give 
Error HH12: Trying to use a non-local installation of Hardhat, which is not supported.
Please install Hardhat locally using npm or Yarn, and try again.

caused by hardhat/packages/hardhat-core/src/internal/core/execution-mode.ts

this comparison won't work as the file path is case insensitive under windows, 
....
23      fs.realpathSync(resolvedPackageJson) === fs.realpathSync(thisPackageJson)
...
quick fix for windows only is change it to 
        return (fs.realpathSync(resolvedPackageJson).toLowerCase() === fs.realpathSync(thisPackageJson).toLowerCase());
a proper fix need to consider all OS.

**Comment by fvictorio** [comment] 2021-05-18 10:09
Hey @railty, this is a duplicate of #1408, so I'm gonna close it, but thanks a lot for investigating the underlying cause, that is very helpful!

**Closed by fvictorio** 2021-05-18 10:09 UTC
