### ISSUE TITLE
hardhat.config.ts > "network" > "accounts" config and its mapping to ethers.getSigners() returns.

### ISSUE THREAD

**Issue by cashonli** [nomiclabs/hardhat#1367] opened 2021-04-03 01:40 UTC
hardhat.config.ts config used for "testnet" networks:
```
...    
networks: { 
    testnet: {
      url: "https://data-seed-prebsc-1-s1.binance.org:8545",
      chainId: 97,
      gasPrice: 20000000000,
      accounts: [
        pks1,
        pks2,
        pks3,
        pks4,
      ]
    },
...
```

in my testscript.js , I have following lines:
```
[owner, addr1, addr2, ...addrs] = await ethers.getSigners();
console.log(owner);
console.log(addr1);
```

I was expecting "owner" will show pks1, "addr1" will show pks2. 
From my testing, I found that:
console.log(owner) --> it prints out the pks1

however, 
console.log(pks1) ---> it says "undefined"

Is this an expected behavior or an issue to investigate?

**Comment by fvictorio** [comment] 2021-05-10 13:46
Hi @cashonli. I can't reproduce this. I created a `rinkeby` network, added two pks, and `ethers.getSigners()` resolved to an array with the two accounts, as expected. I'm going to close this now, but please re-open if you have a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) you can share.

**Closed by fvictorio** 2021-05-10 13:46 UTC
