### ISSUE TITLE
[buidler-truffle] Contracts from within `test/` are sometimes ignored

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/hardhat#431] opened 2020-01-29 23:12 UTC
@shadowfiend reported that this happens in one of his projects. Unfortunately, the project is not yet open source.

We should investigate this in a few weeks when he open sources it.

**Comment by Shadowfiend** [comment] 2020-02-17 21:26
:wave: here's the project -> https://github.com/keep-network/tbtc

I don't have a branch with my buidler fooling around, unfortunately, but if I get a chance I'll see if I can spin one up.

**Comment by fvictorio** [comment] 2020-05-30 21:45
Hey @Shadowfiend, were you able to make that branch? Or do you have some recollection of how this could be reproduced?

**Comment by Shadowfiend** [comment] 2020-05-30 21:48
Hey! I haven’t had a chance no, and we’ve restructured our tests to have tests alongside regular sources for other reasons since then. I do want to do another pass at moving to buidler in the next few weeks, so if I run into it again I’ll circle back here for sure.

**Closed** 2021-06-10 23:24 UTC
