### ISSUE TITLE
hardhat-etherscan needs every chain in chainconfig.ts

### ISSUE THREAD

**Issue by no2chem** [nomiclabs/hardhat#2385] opened 2022-02-15 17:48 UTC
Hardhat-etherscan currently has hard-coded networks in chainconfig.ts. This is problematic if you want to work with a test chain that has its own block explorer, for example, a hardhat test chain, or a new chain that hardhat-etherscan hasn't been setup to work with yet. 

Chainconfig should be able to come from the hardhat.config.ts file. This will reduce the requirement to maintain the chainconfig.ts file.

**Comment by no2chem** [comment] 2022-02-15 17:56
sorry, accidentally submitted without issue text - attached it now

**Comment by alcuadrado** [comment] 2022-02-15 18:42
Thanks for the suggestion, @no2chem. I think this is a duplicate of https://github.com/nomiclabs/hardhat/issues/2173, so I'm closing it.

**Closed by alcuadrado** 2022-02-15 18:42 UTC
