### ISSUE TITLE
Allow telemetry config via environment variable

### ISSUE THREAD

**Issue by Eadword** [nomiclabs/hardhat#1283] opened 2021-02-27 05:39 UTC
Currently playing around with hardhat + docker and I am running into an issue where it does not seem to fail due to not having the correct permissions to write the config file.

If I were building a docker image for this I could just inject the config file, but for right now my goal is to not need to build a new docker image every time I am trying to test it. I am just using docker as a guaranteed running environment.

This is the error I am seeing:
```
Creating uniswap-exporter_scraper_run ... done
/app # npx hardhat
An unexpected error occurred:

Error: EACCES: permission denied, mkdir '/root/.config/hardhat-nodejs'
    at Object.mkdirSync (node:fs:1014:3)
    at Object.mkdirsSync (/app/node_modules/hardhat/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:31:9)
    at getConfigDirSync (/app/node_modules/hardhat/src/internal/util/global-dir.ts:27:6)
    at Object.hasConsentedTelemetry (/app/node_modules/hardhat/src/internal/util/global-dir.ts:109:21)
    at main (/app/node_modules/hardhat/src/internal/cli/cli.ts:120:49) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/root/.config/hardhat-nodejs'
}
npm notice 
npm notice New minor version of npm available! 7.5.3 -> 7.6.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.6.0
npm notice Run npm install -g npm@7.6.0 to update!
npm notice 
npm ERR! code 1
npm ERR! path /app
npm ERR! command failed
npm ERR! command sh -c hardhat

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-27T05_33_11_991Z-debug.log
```

**Comment by alcuadrado** [comment] 2021-02-27 14:39
Hey @Eadword, can you help us reproduce this? What's your Dockerfile? Thanks

**Comment by Eadword** [comment] 2021-02-28 01:58
No dockerfile at this time @alcuadrado, this is primarlly so I can run it on my server without having to mess around with node envs. 

This is my docker-compose:
```yaml
version: '3.8'
services:
  scraper:
    container_name: app
    image: node:15-alpine
    volumes:
      - ./:/app
      - ~:/root   # this is what I did to make it work for now
    working_dir: /app
    entrypoint:
      - npx
    command:
      - hardhat
      - run
      - src/main.ts
```

**Comment by fvictorio** [comment] 2021-03-01 14:20
Maybe the problem here is that we shouldn't show the prompt when hardhat is not being executed in an interactive shell. @Eadword would that solve your problem?

**Comment by Eadword** [comment] 2021-03-01 15:56
That would help, but the actual error seems to be when it tries to write
the config file it fails.

**Comment by fvictorio** [comment] 2021-05-28 22:50
Hey @Eadword, I can't reproduce this. This is what I tried:

```
docker run -it --rm node:15-alpine sh
# inside the container:
mkdir foo && cd 
npm init -y
npm i --save-dev hardhat
npx hardhat
```

**Comment by Eadword** [comment] 2021-05-28 23:30
If that's working I think I was just doing something dumb. It's been a while since I was working on this so it's either been resolved or wasn't really an issue. Thanks for taking the time to look into it.

**Comment by fvictorio** [comment] 2021-05-30 15:39
Oh, ok. I will close this then, but please re-open if you run into this again.

**Closed by fvictorio** 2021-05-30 15:39 UTC
Labels: status:needs-more-info

**Comment by Eadword** [comment] 2021-08-04 15:05
@fvictorio 
Okay, just had reason to dust off the ol' project, definitely still an issue and I can confirm your test does not encounter it.

To reproduce, run

```sh
git clone git@github.com:nomiclabs/hardhat-hackathon-boilerplate.git
cd hardhat-hackathon-boilerplate
# do this outside of docker to simulate my situation of not wanting to build a custom image
npm i
docker run -it --rm -v "$(pwd)":/app -w /app --entrypoint npm node:16-alpine run test
```

And then I get the same error as before. The only fix I have yet found is to mount `~:/root` which is very non-ideal.

I like being able to use docker for testing sometimes so I know it is the same across platforms and when developing I often don't want to make a new docker image after every change. And of course I set it up with my IDE so it is just a quick one-line call.

**Comment by fvictorio** [comment] 2021-08-04 16:31
Hey @Eadword, thanks for letting us know. I think the real underlying issue here is that hardhat shouldn't fail if it doesn't have access to one of those directories.

One possible solution here is to use the local `cache` directory for things like the telemetry config and the downloaded compilers, if the "default" ones cannot be written. I'm going to create a new issue about that.

That being said, I don't think we'll be able to work on that soon. Adding an environment variable, as you originally requested, makes more sense in this case, **but** my guess is that you'll still get this problem when Hardhat will try to download the compilers. So my guess is that using a different mount is your best shot right now.
