### ISSUE TITLE
Hardhat throws a strange error when trying to call smart contract functions

### ISSUE THREAD

**Issue by e74000** [nomiclabs/hardhat#1566] opened 2021-06-18 14:14 UTC
# Hardhat throws a strange error when trying to call smart contract functions
## Description:
When trying to call a smart contract function running on hardhat, it throws confusing errors. (All of this has been tested on the cheapETH network with no errors.)

## Environment:
OS: Manjaro linux 5.10.42
Ver: 2.3.0

## Steps to reproduce:
1. Deploy this smart contract to the hardhat network:
```
pragma solidity 0.8.0;

contract CoolNumber {
    int8 coolNumber = 0;
    
    function GetCoolNumber() public view returns (int8) {
        return coolNumber;
    }
    
    function SetCoolNumber(int8 n) public {
        coolNumber = n;
    }
}
```
2. Compile and then deploy the smart contract
3. Run this python script with ABI.py in the same folder:

**main.py**
```
import web3
from ABI import abi
import time

Web3 = web3.Web3

polling_interval = 5
address = '0x5FbDB2315678afecb367f032d93F642f64180aa3' # replace this with the smart contract address


def main():
    w3 = Web3(Web3.HTTPProvider("http://127.0.0.1:8545"))
    contract = w3.eth.contract(address=address, abi=abi)
    while True:
        x = contract.functions.GetCoolNumber().call()
        print(x)
        time.sleep(polling_interval)


if __name__ == "__main__":
    main()
```
**ABI.py**
```
abi = [
    {
        "inputs": [
            {
                "internalType": "int8",
                "name": "n",
                "type": "int8"
            }
        ],
        "name": "SetCoolNumber",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    },
    {
        "inputs": [],
        "name": "GetCoolNumber",
        "outputs": [
            {
                "internalType": "int8",
                "name": "",
                "type": "int8"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    }
]
```
4. Alternatively in the hardhat console type `const coolNumber = await (await ethers.getContractFactory("CoolNumber")).attach("0x5FbDB2315678afecb367f032d93F642f64180aa3")`
5. Then type: `await coolNumber.GetCoolNumber()` but replace the address with the contract address.

## Actual behaviour:
In hardhat console when trying to call `GetCoolNumber()`:
```
> await token.GetCoolNumber()
Uncaught:
Error: call revert exception (method="GetCoolNumber()", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.3.0)
    at step (/home/manjaro/gitstuff/solidity-stuff/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Contract.<anonymous> (/home/manjaro/gitstuff/solidity-stuff/node_modules/@ethersproject/contracts/src.ts/index.ts:321:44)
    at Interface.decodeFunctionResult (/home/manjaro/gitstuff/solidity-stuff/node_modules/@ethersproject/abi/src.ts/interface.ts:384:23)
    at Logger.throwError (/home/manjaro/gitstuff/solidity-stuff/node_modules/@ethersproject/logger/src.ts/index.ts:225:20)
    at Logger.makeError (/home/manjaro/gitstuff/solidity-stuff/node_modules/@ethersproject/logger/src.ts/index.ts:213:28) {
  reason: null,
  code: 'CALL_EXCEPTION',
  method: 'GetCoolNumber()',
  errorArgs: null,
  errorName: null,
  errorSignature: null,
  address: '0x5FbDB2315678afecb367f032d93F642f64180aa3',
  args: [],
  transaction: {
    data: '0xdba6cc19',
    to: '0x5FbDB2315678afecb367f032d93F642f64180aa3',
    from: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
  }
}
```
In python trying to call `GetCoolNumber()`:
```
Traceback (most recent call last):
  File "/home/manjaro/PycharmProjects/onest/venv/lib/python3.9/site-packages/web3/contract.py", line 1513, in call_contract_function
    output_data = web3.codec.decode_abi(output_types, return_data)
  File "/home/manjaro/PycharmProjects/onest/venv/lib/python3.9/site-packages/eth_abi/codec.py", line 181, in decode_abi
    return decoder(stream)
  File "/home/manjaro/PycharmProjects/onest/venv/lib/python3.9/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/home/manjaro/PycharmProjects/onest/venv/lib/python3.9/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/home/manjaro/PycharmProjects/onest/venv/lib/python3.9/site-packages/eth_abi/decoding.py", line 173, in decode
    yield decoder(stream)
  File "/home/manjaro/PycharmProjects/onest/venv/lib/python3.9/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/home/manjaro/PycharmProjects/onest/venv/lib/python3.9/site-packages/eth_abi/decoding.py", line 198, in decode
    raw_data = self.read_data_from_stream(stream)
  File "/home/manjaro/PycharmProjects/onest/venv/lib/python3.9/site-packages/eth_abi/decoding.py", line 305, in read_data_from_stream
    raise InsufficientDataBytes(
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/manjaro/PycharmProjects/onest/main.py", line 21, in <module>
    main()
  File "/home/manjaro/PycharmProjects/onest/main.py", line 15, in main
    x = contract.functions.GetCoolNumber().call()
  File "/home/manjaro/PycharmProjects/onest/venv/lib/python3.9/site-packages/web3/contract.py", line 957, in call
    return call_contract_function(
  File "/home/manjaro/PycharmProjects/onest/venv/lib/python3.9/site-packages/web3/contract.py", line 1530, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not transact with/call contract function, is contract deployed correctly and chain synced?

Process finished with exit code 1
```

## Logs:
In the hardhat node logs:
```
eth_call
  WARNING: Calling an account which is not a contract
  From: 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:   0x5fbdb2315678afecb367f032d93f642f64180aa3
```

**Comment by fvictorio** [comment] 2021-06-18 18:07
As the warning says, you are making a `eth_call` in an account with no code. That usually happens when you use two different instances of the hardhat network. For example, if you have a script that deploys the contract and another that uses the contract, and you do `hh run deploy.js && hh run useContract.js`, each script will create, use and destroy a temporary, in-process hardhat network.

Another typical reason people get this error is when they start a node with `hh node` in one terminal and run their script in another terminal by doing `hh run useContract.js` instead of `hh run --network localhost useContract.js`.

I'm going to close this because it's very unlikely this is a bug. Please use [our discord server](https://hardhat.org/discord) if you have more questions about this.

**Closed by fvictorio** 2021-06-18 18:07 UTC

**Comment by Mowgli9** [comment] 2022-04-17 15:36
`npx hardhat run scripts/simple.js --network localhost`

**Comment by developerasun** [comment] 2022-06-12 13:54
> As the warning says, you are making a `eth_call` in an account with no code. That usually happens when you use two different instances of the hardhat network. For example, if you have a script that deploys the contract and another that uses the contract, and you do `hh run deploy.js && hh run useContract.js`, each script will create, use and destroy a temporary, in-process hardhat network.
> 
> Another typical reason people get this error is when they start a node with `hh node` in one terminal and run their script in another terminal by doing `hh run useContract.js` instead of `hh run --network localhost useContract.js`.
> 
> I'm going to close this because it's very unlikely this is a bug. Please use [our discord server](https://hardhat.org/discord) if you have more questions about this.

This worked like a charm! I was checking local hardhat network logs and found a warning statement like below. 

![account-no-contract](https://user-images.githubusercontent.com/83855174/173236468-b4391497-2439-4b6b-ac75-9dcc361c52ee.png)

and in a dapp I was working on, it threw below errors with metamask transaction failure.

![unhandled-rejection-metamask5](https://user-images.githubusercontent.com/83855174/173236550-c4fab0fd-d34f-4723-ac4b-11034c01b915.png)

once I re-deployed a contract with localhost network option(I did it like --network hardhat, probably created one more hardhat instance) and worked fine.

**Comment by qwerty199991** [comment] 2022-10-28 14:05
I got the same error and after reading comments above I got it: 
I deployed it without --network localhost so following actions even with --network localhost caused error.

**Comment by Rahimjackass** [comment] 2022-11-19 14:43
> As the warning says, you are making a `eth_call` in an account with no code. That usually happens when you use two different instances of the hardhat network. For example, if you have a script that deploys the contract and another that uses the contract, and you do `hh run deploy.js && hh run useContract.js`, each script will create, use and destroy a temporary, in-process hardhat network.
> 

Sir, Do you mean it will deploy our project on a completely different network if we use `"npx hardhat run scripts/sample.js"` rather `"npx hardhat run scripts/sample.js --network localhost"`?? So where is the network that the first deployment command points to? 

localhost is different from the default network of the Hardhat? 

I guess localhost refers to the network we see on the terminal by typing "npx hardhat node"

Please correct me wherever I am wrong!

Thanks

**Comment by fvictorio** [comment] 2022-11-19 17:41
> So where is the network that the first deployment command points to?

When you don't specify a network, the execution will be done in a temporary, in-process Hardhat Network that is created and destroyed with your command.

This is useful, for example, when you are running your tests. Otherwise you would have to do something like "start a node in one terminal, run `hh test --network localhost` in another terminal, then kill the node in the first one". You can think about the in-process Hardhat Network as a shortcut for that (there are other subtle differences though, like the fact that there's no HTTP involved).

**Comment by archerkeyboard** [comment] 2022-11-20 14:41
This is an interesting issue that I'm facing currently. What I'm doing is forking BSC like this
`npx hardhat node --fork https://bsc-dataseed2.binance.org`
running a command via `npx hardhat run --network localhost final\ganache.js`

It's weird - the code in ganache.js does not change. Sometimes the script passes without any issues and sometimes the node gives out the warnings which fails the script. I believe this is still an ongoing issue on HH - I still cannot figure out exactly what is causing the issue, but it's still there.

hardhat version 2.12.2

**Comment by fvictorio** [comment] 2022-11-21 16:34
@archerkeyboard please open a new issue if you can provide a
[minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by archerkeyboard** [comment] 2022-11-27 14:18
> @archerkeyboard please open a new issue if you can provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

https://github.com/NomicFoundation/hardhat/issues/3379
