### ISSUE TITLE
Hardhat installation not recognized when install with GitBash

### ISSUE THREAD

**Issue by Leon-Africa** [nomiclabs/hardhat#1438] opened 2021-05-03 15:52 UTC
As referenced: https://github.com/nomiclabs/hardhat/issues/1400

**Reproduction steps:**
Using [GitBash](https://git-scm.com/downloads) on Windows (assuming GitBash is being used)

````
npm init --yes 
````
````
npm i --save-dev hardhat
````
````
npx hardhat
````

Results in error:
````
Error HH1: You are not inside a Hardhat project.

For more info go to https://hardhat.org/HH1 or run Hardhat with --show-stack-traces
````

Interim solution: https://github.com/nomiclabs/hardhat/issues/1400#issuecomment-824097242

**Comment by alcuadrado** [comment] 2021-05-03 15:54
Thanks for opening this issue, @Leon-Africa.

This is a duplicate of #1408, so I'm closing it.

**Closed by alcuadrado** 2021-05-03 15:54 UTC
