### ISSUE TITLE
`allowUnlimitedContractSize` doesn't work for deployments within Solidity

### ISSUE THREAD

**Issue by gorgos** [nomiclabs/hardhat#660] opened 2020-06-25 02:13 UTC
Getting the error:

```
 Error: Transaction reverted: trying to deploy a contract whose code is too large
      at MyContract.constructor (contracts/MyContract.sol:65)
      at MyContractFactory.createContract(contracts/MyContractFactory.sol:71)
```

Using latest version: `1.3.8`.

**Comment by alcuadrado** [comment] 2020-06-25 02:22
You mean that it does work for deploying contracts from your js code, but not for factories?

If that's the case, I'd report it and fix it in ethereumjs-vm.

**Comment by gorgos** [comment] 2020-06-25 02:34
@alcuadrado Exactly.

**Comment by alcuadrado** [comment] 2020-06-29 00:13
Hey @gorgos, do you have a link to a repo where I can reproduce this?

**Comment by kendricktan** [comment] 2020-07-10 01:01
@alcuadrado Here's an example repo that produces the problem

https://github.com/kendricktan/ethereumjs-vm-factory-unlimited

**Comment by alcuadrado** [comment] 2020-07-10 15:38
Thanks for putting up this, @kendricktan!

Something really weird is going on here. I looks like an actual OOG error, that Buidler is encoding poorly. I modified the config little so that the `gas` and `blockGasLimit` are 1000M now, and the transaction runs forever. This makes me think that there's an infinite loop introduced by solidity, or that the VM is seriously broken.

**Comment by alcuadrado** [comment] 2020-07-10 16:18
Ok, after tracing the transaction further, it doesn't seem to be an infinite loop, but your contract is actually doing a lot of work.

This isn't an EIP170 error though, as that is related to the size of the runtime bytecode, and not the amount of work done in the constructor. 

Buidler is failing to show this error clearly though. We have to dig deeper to identify why and fix it.

**Comment by kendricktan** [comment] 2020-07-10 23:48
You're right! Bumping the gas up makes it work. Interesting.... Lots of these little gotchas :sweat_smile:

**Comment by alcuadrado** [comment] 2020-07-10 23:58
Sorry for the inconvenience, I appreciate you reported it.

Can you keep your reproduction repo until we have time to fix this?

**Comment by gorgos** [comment] 2020-07-13 05:29
I'm actually seeing this error now even in Truffle fixtures.

`solc v0.6.10`

```
Contract: MyContract
       "before all" hook: Running truffle fixture if available in "Contract: MyContract":
     Error: Transaction reverted: trying to deploy a contract whose code is too large
      at MyContract.constructor (contracts/MyContract.sol:17)
```

`solc v0.6.11`

```
 Contract: MyContract
       "before all" hook: Running truffle fixture if available in "Contract: MyContract":
     Error: Returned error: Transaction run out of gas
```

**Comment by kendricktan** [comment] 2020-07-13 10:59
@gorgos The solution was bumping the `gas` value in `buidler.config.js`. E.g.

```javascript
module.exports = {
  networks: {
    buidlerevm: {
      gas: 12000000,
      blockGasLimit: 0x1fffffffffffff,
      allowUnlimitedContractSize: true,
      timeout: 1800000
    }
  }
};

```

**Comment by alcuadrado** [comment] 2020-07-13 17:44
> I'm actually seeing this error now even in Truffle fixtures.
> 
> `solc v0.6.10`
> 
> ```
> Contract: MyContract
>        "before all" hook: Running truffle fixture if available in "Contract: MyContract":
>      Error: Transaction reverted: trying to deploy a contract whose code is too large
>       at MyContract.constructor (contracts/MyContract.sol:17)
> ```

This may be a bug. Can you help us reproduce it?

**Comment by gorgos** [comment] 2020-07-13 20:11
@kendricktan That unfortunately didn't do the trick for me.

@alcuadrado Happy to, but the project I have the issue with is a fairly complex system and closed-source. I'll try to reproduce it in a new project, but may not succeed. Wish me luck.

**Comment by gorgos** [comment] 2020-07-14 03:52
@alcuadrado No special setup required actually: https://github.com/gorgos/buidler-unlimited-contract-size-bug.

**Comment by gorgos** [comment] 2020-07-25 04:20
Unfortunately still exists in 1.4.0, I updated the repo accordingly.

**Comment by PaulRBerg** [comment] 2020-10-24 10:50
@kendricktan's solution works, but there are some nuances:

+ If "gas" is set to "auto", Hardhat fails to correctly calculate the amount of gas required to deploy a contract that deploys other contract(s).
+ If "gas" is hardcoded to a very high value, it works.

**Comment by zhengger** [comment] 2020-10-25 11:55
I have a question. How to deploy such oversized contract on mainnet where the block gas limits to 12,500,000 gas?
IMO, maybe the problem is rooted from the contract  but not the environment settings.

**Comment by gorgos** [comment] 2020-10-25 19:43
> IMO, maybe the problem is rooted from the contract but not the environment settings.

There are still several reasons why you might have contracts that are too large in Hardhat:

- not using the optimizer to ensure correct stack lines
- a contract still heavily being developed and the downsizing is planned for later
- using a private network with higher gas limits

**Comment by ztcrypto** [comment] 2021-02-24 23:13
Still getting this issue
Contract: LoanTokenLending
       "before each" hook for "test lend to the pool":
     Error: Transaction reverted: trying to deploy a contract whose code is too large.
     
     Actually trying to test contracts but this error is showing on deploying command.
     Is the solution manual setting?

**Comment by novaknole** [comment] 2021-02-26 08:43
@ztcrypto 

I had this similar issue as of now too. Make sure to also include `blockGasLimit: 0x1fffffffffffff` in the settings, otherwise, nothing else helps. 

Mine looks like this:

```js
hardhat: {
      throwOnTransactionFailures: true,
      throwOnCallFailures: true,
      allowUnlimitedContractSize: true,
      blockGasLimit: 0x1fffffffffffff,
      accounts: accounts()
}
```

**Comment by ztcrypto** [comment] 2021-02-26 13:13
Thanks @novaknole I will try again.

**Comment by fvictorio** [comment] 2021-06-10 23:15
I'm not sure if there's something to do on our side here, so I'm going to tentatively close this issue. Please re-open if there's something we can do about this.

**Closed by fvictorio** 2021-06-10 23:15 UTC

**Comment by MZubairLohar** [comment] 2021-07-31 16:03
// solidity: "0.8.0",
  solidity: {
    version: "0.8.0",
    settings: {
      optimizer: {
        enabled: true,
        runs: 200
      }
    }
  },
i simply added this to hardhat config . problem solved. optimizer enable true and runs 200

**Comment by murderteeth** [comment] 2021-09-23 06:33
fwiw, just this worked for me
```
  networks: {
    hardhat: {
      allowUnlimitedContractSize: true
    }
  },
```

**Comment by samgville** [comment] 2021-12-06 12:16
Hey, I'm trying to deploy to BSC Testnet using Hardhat and I have added the allowUnlimitedContractSize: true, Optimizer enabled with 200 runs, and put large gas numbers and still getting the `ProviderError: max code size exceeded.`
Is anyone experiencing the same thing?

**Comment by alcuadrado** [comment] 2021-12-07 22:18
@samgville that feature is specific to Hardhat Network. It has no effect on live testnets.

**Comment by samgville** [comment] 2021-12-21 21:54
@alcuadrado thanks for your reply. I'm curious then how is it possible to see contracts deployed on mainnets that exceed the size limit for each contracts? I've seen some of them use saddle-eth to deploy and apparently they can turn on the AllowUnlimitedContractSize for testnets.

**Comment by MZubairLohar** [comment] 2022-01-01 09:17
networks: {
    hardhat: {
      allowUnlimitedContractSize: true
    }
  }, 

this also works as well as just enable run on 1 not 200 will do trick for few as well

**Comment by alcuadrado** [comment] 2022-01-06 15:13
> apparently they can turn on the AllowUnlimitedContractSize for mainnets.

That's impossible, as that feature doesn't even exist in other chains. it's an ethereumjs thing.

Those contracts are probably compiled with a different version of solc or with different optimizer settings.

**Comment by enderphan94** [comment] 2022-01-29 15:22
Just enable the optimizer in hardhat.config.js

```
solidity: {
    version: "0.7.5",
    settings: {
      optimizer: {
        enabled: true,
        runs: 200
      }
    }
  },
```

**Comment by redigaffi** [comment] 2022-04-18 13:33
For me nothing is working, the whole point of deploying without optimization is to make debugging easier. If you enable optimization the debugger wont work as well. Optimization should only be needed for mainnet...
