### ISSUE TITLE
EthModule._estimateGasAction seems fail on hardhat

### ISSUE THREAD

**Issue by dexcell** [nomiclabs/hardhat#976] opened 2020-10-30 20:57 UTC
My test deploy script is running fine using buidler, but on hardhat it's error. Seems failed to estimate gas action?
````
 at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at EthModule._estimateGasAction (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:390:9)
      at HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:101:14)
      at EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/ethers-provider-wrapper.ts:13:20)
````
Changing config like this works, but this issue need to be investigated.
````
hardhat: {
            allowUnlimitedContractSize: true,
            gas: 12000000,
            blockGasLimit: 0x1fffffffffffff,
        }
````

**Comment by fvictorio** [comment] 2020-11-02 14:17
Hey @dexcell, is your project public? Or can you at least share how your deploy script looks like (and which line throws the error)?

**Comment by dexcell** [comment] 2020-11-04 05:48
@fvictorio 
Thanks for the attention, its not public, i will try gain more info and post here, but it seems does something with the gas since adding the `gas` and `blockGasLimit` fixed it.

as for now i go back to buidler since i was scared a bit and don't wan't to waste time fight errors that's not on my code.

**Comment by dexcell** [comment] 2020-11-07 16:47
@fvictorio 
I have tried investigate it again.

So, my current situation, i have a unit test deploy script running perfectly on buidler,
Then i copy all the contracts to hardhat, and try run the same test deploy script.

When i run it the test on hardhat, it will shows 
`Error: Transaction reverted: trying to deploy a contract whose code is too large`
This does not happen on buidler, only on hardhat.

If add this, to hardhat config, i can deploy my test correctly. 
```
gas: 12000000,
blockGasLimit: 0x1fffffffffffff,
```

**Comment by dexcell** [comment] 2020-11-08 12:48
After i test it more, i more inclined to think this is buidler bug, rather than hardhat.
Since my contract can be deployed on buidler EVM, but not on ganache. 
After i split my contract to reduce the size, it can deployed on ganache and hardhat without changing any config.

**Comment by dexcell** [comment] 2020-11-10 02:42
@fvictorio 
Sorry, i reopened the issue again:

I can't deploy to ganache with forked mainnet, using hardhat, while buidler with same config works fine.

````
ProviderError: VM Exception while processing transaction: out of gas
    at HttpProvider.request (/Users/e/Documents/EthereumProjects/dvd/node_modules/hardhat/src/internal/core/providers/http.ts:45:19)
    at HDWalletProvider.request (/Users/e/Documents/EthereumProjects/dvd/node_modules/hardhat/src/internal/core/providers/accounts.ts:125:36)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at EthersProviderWrapper.send (/Users/e/Documents/EthereumProjects/dvd/node_modules/@nomiclabs/hardhat-ethers/src/ethers-provider-wrapper.ts:13:20)

````

hardhat config
````
ganache: {
            url: "http://localhost:8545",   // CLI
            chainId: 1337,
            gasPrice: "auto",
            accounts: {
                mnemonic: private.mnemonic.ganache,
                path: "m/44'/60'/0'/0",
            },
            timeout: 15 * 60 * 1000, // 15 mins timeout
        },
````

**Comment by fvictorio** [comment] 2020-11-11 11:43
Do you have a public repository?

If not, can you try to give us some minimal reproduction steps?

**Comment by fvictorio** [comment] 2020-12-22 12:02
Closing this for lack of reproduction steps, but feel free to re-open with them.

**Closed by fvictorio** 2020-12-22 12:02 UTC
Labels: status:needs-more-info
