### ISSUE TITLE
Compilation error message not parsed

### ISSUE THREAD

**Issue by morrigan** [nomiclabs/hardhat#1270] opened 2021-02-23 07:53 UTC
When running `compile` with `--verbose`

```
hardhat:core:hre Running task compile:solidity:get-compilation-job-for-file +4ms
hardhat:core:compilation-job '.../contracts/WhitelistingContract.sol' couldn't be compiled. Reason: '[object Object]'
```

Expected to see a reason message.

Still not sure why but most probably because of another contract import. The compilation error below says `incompatible Solidity pragmas` but that's not the case.

**Comment by fvictorio** [comment] 2021-02-23 13:46
And this also doesn't show the compilation error at all at the end of the task (even without `--verbose`)?

If so, please let us know how to reproduce it, since it would be a huge bug.

**Comment by morrigan** [comment] 2021-03-02 07:49
> And this also doesn't show the compilation error at all at the end of the task (even without `--verbose`)?
> 
> If so, please let us know how to reproduce it, since it would be a huge bug.

Just that there are incompatible Solidity pragmas, however, all contracts have the same pragma. I can't open source everything but I'll try to make a reproducible demo.

**Comment by fvictorio** [comment] 2021-05-28 22:52
Closing this for now. Please re-open if you have a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) you can share.

**Closed by fvictorio** 2021-05-28 22:52 UTC
