### ISSUE TITLE
hardhat-etherscan does not work as expect.

### ISSUE THREAD

**Issue by Skyge** [nomiclabs/hardhat#1036] opened 2020-11-19 07:45 UTC
I am trying to use `hardhat-etherscan` to verify contract automatically, but it does not work as my expect, cause I only want to verify a contract, but it uploads all my contracts, my `hardhat.config.js` is:
```js
require("dotenv").config();
require("@nomiclabs/hardhat-waffle");
require("@nomiclabs/hardhat-etherscan");
require("hardhat-deploy-ethers");

const privateKey = process.env.PRIVATE_KEY;
const infuraKey = process.env.INFURA_KEY;

module.exports = {
  networks: {
    kovan: {
      url: `https://kovan.infura.io/v3/${infuraKey}`,
      accounts: [`0x${privateKey}`]
    }
  },
  solidity: {
    version: "0.6.12",
    settings: {
      optimizer: {
        enabled: true,
        runs: 2000
      }
    }
  },
  etherscan: {
    apiKey: process.env.ETHERSCAN_KEY
  }
};
```
My deployed scripts `deploy.js` is: 
```js
async function main() {
    const [deployer] = await ethers.getSigners();

    console.log(
        "Deploying contracts with the account:",
        deployer.address
    );

    console.log("Account balance:", (await deployer.getBalance()).toString());

    const Token = await ethers.getContractFactory("Token");
    const token = await Token.deploy("Mock Token", "MT");

    console.log("Token address:", token.address);
}

main()
.then(() => process.exit(0))
.catch(error => {
    console.error(error);
    process.exit(1);
});
```

my contract is:
```solidity
pragma solidity 0.6.12;

import "@openzeppelin/contracts-upgradeable/token/ERC20/ERC20Upgradeable.sol";

contract Token is ERC20Upgradeable{
    constructor(
        string memory _name,
        string memory _symbol
    ) public {
        __ERC20_init(_name, _symbol);
    }

    function mint(address account, uint256 amount) public {
        _mint(account, amount);
    }
}
```

**Comment by scnale** [comment] 2020-11-19 16:51
I'm closing this as a duplicate of #804. A fix for this is coming soon, btw.

**Closed by scnale** 2020-11-19 16:51 UTC
