### ISSUE TITLE
Add the possibility to create a custom fork network from hardhat config

### ISSUE THREAD

**Issue by sshmaxime** [nomiclabs/hardhat#1694] opened 2021-07-19 13:45 UTC
It would be very useful to be able to create a custom network fork from the hardhat config. Like so:

```ts
    networks: {
        fork-mainnet: {
            accounts: [loadKey('mainAccount')],
            forking: {
                enabled: true,
                url: 'https://eth-mainnet.alchemyapi.io/v2/',
                blockNumber: 12856166
            }
        },
    },
```

**Comment by fvictorio** [comment] 2021-07-19 17:37
Closing as a duplicate of https://github.com/nomiclabs/hardhat/issues/1111, but please re-open if you think that's not the case.

**Closed by fvictorio** 2021-07-19 17:37 UTC
