### ISSUE TITLE
The Hardhat Network tracing engine could not be initialized

### ISSUE THREAD

**Issue by 852Kerfunkle** [nomiclabs/hardhat#1743] opened 2021-08-02 09:20 UTC
Running a `hardhat node`, I'm getting this error when mapping an Interface. Also fails when mapping contract.

`The Hardhat Network tracing engine could not be initialized. Run Hardhat with --verbose to learn more.
  hardhat:core:hardhat-network:node Hardhat Network tracing disabled: ContractsIdentifier failed to be initialized. Please report this to help us improve Hardhat.
  hardhat:core:hardhat-network:node  TypeError: Cannot read property 'startsWith' of undefined`

hardhat 2.5.0.

```
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.6;

interface IContractA { }

contract Registry {
    mapping(IContractA => bool) public isRegistered;
}
```

What am I missing out on not running the network tracing engine? Should I rather use a mapping from address in the meantime?

**Comment by fvictorio** [comment] 2021-08-02 13:41
> What am I missing out on not running the network tracing engine?

You won't get proper stack traces, nor inferred errors (things like "call to a non-contract account"). But you can still use hardhat: compiling, testing, running a node, etc. will continue working fine.

**Comment by paulrberg** [comment] 2021-08-11 13:37
> But you can still use hardhat: compiling, **testing**, running a node, etc. will continue working fine.

Unfortunately, without the tracing engine, you can't test Solidity v0.8.4 custom errors, because of #1618.

**Comment by paulrberg** [comment] 2021-08-11 13:50
Duplicate of #1564.

**Comment by fvictorio** [comment] 2021-08-12 11:56
Good catch @paulrberg!

**Closed by fvictorio** 2021-08-12 11:56 UTC
Labels: package:hardhat-core
