### ISSUE TITLE
buidler hangs during compile

### ISSUE THREAD

**Issue by travisdmathis** [nomiclabs/hardhat#667] opened 2020-06-29 14:23 UTC
https://github.com/pandao-bamboo/contracts/tree/feature/liquidity

when i try and compile this branch it hangs during the compile and killing the process DOES NOT kill the background process.. I continue to have a node process running at 98% CPU in the background.  The offending function can be found here

https://github.com/pandao-bamboo/contracts/blob/feature/liquidity/contracts/lib/StorageHelper.sol#L101

If i comment this out, everything compiles, but i'm not doing anything in this function I don't do anywhere else.

To recreate clone repo, checkout branch feature/liquidity run yarn test, but be sure to kill the background process or it will be running at near 100% CPU.

**Comment by dmvt** [comment] 2020-06-29 15:06
I've confirmed this result on my macbook pro.

**Comment by fvictorio** [comment] 2020-06-29 15:10
Hey @travisdmathis, which version of node are you using?

**Comment by fvictorio** [comment] 2020-06-29 15:17
Oh, nevermind, I could reproduce it (node 10, ubuntu).

For the record: using the compiler directly with the standard json doesn't hang.

**Comment by fvictorio** [comment] 2020-06-29 15:58
More data points:

- Disabling the optimizer avoids the hanging but throws an internal compilation error.
- Changing to solc 0.6.10 fixes the problem (both with and without the optimizer).

**Comment by travisdmathis** [comment] 2020-06-29 16:59
changed to solc 0.6.10 seems to have resolved the issue.

**Comment by fvictorio** [comment] 2020-06-29 17:04
Nice!

I think this issue should be kept open though, because the behavior of the child processes still running after cancelling the compilation seems like a problem.

**Comment by fvictorio** [comment] 2021-06-10 23:14
I'm going to close this one since I don't think we'll work on this anytime soon. Please re-open if someone runs into this with newer versions of solidity.

**Closed by fvictorio** 2021-06-10 23:14 UTC
