### ISSUE TITLE
Does Hardhat node support events?

### ISSUE THREAD

**Issue by vicnaum** [nomiclabs/hardhat#1181] opened 2021-01-15 12:27 UTC
I'm running the same file with Ganache node and with Hardhat node, using web3js.

In Ganache the transaction receipt normally has events in it.
In Hardhat the events property is empty.

Does it support events or it's not implemented yet?

Ganache:
![image](https://user-images.githubusercontent.com/5636644/104727287-5708a680-5735-11eb-8bc0-12c48948b088.png)

Hardhat:
![image](https://user-images.githubusercontent.com/5636644/104727319-6556c280-5735-11eb-8a8d-e8eed5328c50.png)

**Comment by alcuadrado** [comment] 2021-01-15 12:35
Hey, thanks for opening this issue. This is a duplicate of https://github.com/nomiclabs/hardhat/issues/588, so I'm closing it. 

The good news is that we are currently fixing it in #1163

**Comment by alcuadrado** [comment] 2021-01-15 15:38
I think I may be wrong about this. Reopening it until we further investigate it.

**Comment by vicnaum** [comment] 2021-01-15 16:15
Strange, but after submitting the bug - it started to work - I don't know why - even though I restarted it a couple of times before.

**Comment by fvictorio** [comment] 2021-01-26 19:04
@vicnaum glad to hear that. Please re-open if it happens again and you have some way to reproduce it.

**Closed by fvictorio** 2021-01-26 19:04 UTC

**Comment by rad-p** [comment] 2021-04-13 17:41
I do face the same issues, same codebase works with ganache, but not with hardhat node

**Comment by fvictorio** [comment] 2021-04-14 14:24
@rad-p do you have a reproducible example?
