### ISSUE TITLE
Mocha test config not used when testing individual file

### ISSUE THREAD

**Issue by RyanRHall** [nomiclabs/hardhat#1886] opened 2021-09-17 00:20 UTC
Config states that mocha options can be passed through hardhat.config.js like so...

```ts
export default {
  solidity: '0.8.6',
  mocha: {
    file: 'test/hooks.ts',
  }
}
```

test/hooks.ts may contain something like:
```ts
afterEach(async () => {
  // do cleanup task
  console.log('running cleanup!')
})
```

This works if we run the entire test suite ex:

```
$ hardhat test

  MyContract
    someFunction()
      ✓ Should ... whatever (83ms)
running cleanup!
      ✓ Should ... whatever 2 (64ms)
running cleanup!
```

however, it _ignores_ the hooks file if we test an individual file like so...

```
$ hardhat test ./test/MyContract.test.ts

  MyContract
    someFunction()
      ✓ Should ... whatever (83ms)
      ✓ Should ... whatever 2 (64ms)
```

Maybe this is an issue with mocha instead?

**Comment by alcuadrado** [comment] 2021-09-17 12:14
Thanks for reporting this. I'm closing it, as it's a duplicate of #1806. I think you'll find that discussion interesting. Unfortunately, we can't prioritize this atm.

**Closed by alcuadrado** 2021-09-17 12:14 UTC
