### ISSUE TITLE
Intermittent failure calling ethers.provider.getBlock

### ISSUE THREAD

**Issue by aaronovz1** [nomiclabs/hardhat#1183] opened 2021-01-15 19:52 UTC
Running hardhat network mainnet fork.

`getBlock` returns null object sometimes within a test.

https://github.com/Dracula-Protocol/contracts-v2/blob/main/test/RewardPool.spec.ts#L127

In the example above, the first call to `advanceBlockAndTime`  fails but the second one succeeds.

**Comment by Tonyhaenn** [comment] 2021-01-18 19:24
I’m also seeing this happen

**Comment by fvictorio** [comment] 2021-01-25 12:03
I think this function is wrong:

https://github.com/Dracula-Protocol/contracts-v2/blob/bbaebb450b35d209fa257de9e3a6ed45d86649b5/test/utils.ts#L72-L83

You need to call `evm_increaseTime` **before** `evm_mine`

**Comment by aaronovz1** [comment] 2021-01-26 00:43
Hey @fvictorio, I tried swapping them around but I still see the same problem. I also don't think it makes sense logically since having it in that order works fine in some cases but not in others.

**Comment by fvictorio** [comment] 2021-01-26 18:58
I see. I think we'll need a more reproducible example before looking into this.

Ideally you can make a minimal repo that reproduces the problem. Alternatively, please give us detailed steps on how to reproduce it in your repo (clone it, checkout X commit, run these commands).

**Comment by Tonyhaenn** [comment] 2021-01-27 13:25
I started working something up last night. I'll post a repo in the next few days

**Comment by Tonyhaenn** [comment] 2021-01-31 21:02
https://github.com/Tonyhaenn/hh-time-travel

There’s a repo that reproduces the issue and provides a workaround.

**Comment by Tonyhaenn** [comment] 2021-02-01 00:27
A little explainer on that repo:
I created a toy contract that I could interact with to test that the block.timestamp was moving forward.

I have two different implementations that advance the time in the test.js file. You can see that the first version (the flawed one) works _only_ when the contract state doesn’t update. It passes in the first test suite, but as soon as I start updating the contract state by incrementing a uint256, I get the failure in the second test suite. 

In the third suite, I show that the workaround solution works

**Comment by marcelomorgado** [comment] 2021-03-17 11:23
I've faced the same issue here and as a workaround, I've changed from: `await provider.getBlock(await provider.getBlockNumber())` to `await provider.getBlock('latest')`

**Comment by fvictorio** [comment] 2021-03-17 14:51
I think the original issue this is caused by https://github.com/nomiclabs/hardhat/issues/1247 @marcelomorgado are you using snapshots too?

**Comment by marcelomorgado** [comment] 2021-03-17 16:20
> I think the original issue this is caused by #1247 @marcelomorgado are you using snapshots too?

Yep

**Comment by aaronovz1** [comment] 2021-03-20 20:30
> I've faced the same issue here and as a workaround, I've changed from: `await provider.getBlock(await provider.getBlockNumber())` to `await provider.getBlock('latest')`

This solved the issue I was having. Cheers.

**Comment by fvictorio** [comment] 2021-03-23 15:49
Closing in favor of #1247.

**Closed by fvictorio** 2021-03-23 15:49 UTC
Labels: priority:high, status:needs-research
