### ISSUE TITLE
`hre.ethers.provider.connection.url` doesn't return current network

### ISSUE THREAD

**Issue by markmiro** [nomiclabs/hardhat#1798] opened 2021-08-15 23:22 UTC
A more robust version of the below code is here: https://github.com/markmiro/hardhat-ethers-network-confusion

./package.json
```json
{
  "devDependencies": {
    "@nomiclabs/hardhat-ethers": "2.0.2",
    "ethers": "5.4.4",
    "hardhat": "2.6.0"
  }
}

```
./hardhat.config.js
```javascript
require("@nomiclabs/hardhat-ethers");

module.exports = {
  networks: {
    ropsten: {
      url: `https://eth-ropsten.alchemyapi.io/v2/3RI0h7l9dI7NPpIWBKiASq6IV0cUFbRQ`,
    },
  },
  solidity: "0.8.4",
};
```

./script.js
```javascript
const hre = require("hardhat");

async function main() {
  console.log("Network url:", hre.network.config.url);
  console.log("Provider url:", hre.ethers.provider.connection.url);
}

main()
```

Run on localhost network, and results look fine:

```
% npx hardhat run script.js --network localhost
Network url: http://127.0.0.1:8545
Provider url: http://localhost:8545
```

However, running on ropsten yields unexpected result:

```
% npx hardhat run script.js --network ropsten  
Network url: https://eth-ropsten.alchemyapi.io/v2/3RI0h7l9dI7NPpIWBKiASq6IV0cUFbRQ
Provider url: http://localhost:8545
```

**Expected**:
`Provider url: https://eth-ropsten.alchemyapi.io/v2/3RI0h7l9dI7NPpIWBKiASq6IV0cUFbRQ`

**Actual**:
`Provider url: http://localhost:8545`

**Comment by relston** [comment] 2021-08-17 07:54
I have the same issue. Can connect to the correct network using the `--network` param.

**Comment by fvictorio** [comment] 2021-08-20 17:54
Duplicate of #1138.

Notice that you can use `hre.network.name` to know which network is being used.

You can also use `hre.network.config.url` to get the URL, but that will be undefined when connecting to the `hardhat` network.

**Closed by fvictorio** 2021-08-20 17:54 UTC
