### ISSUE TITLE
Add functionality to prettify BigNumber

### ISSUE THREAD

**Issue by mrthankyou** [nomiclabs/hardhat#2109] opened 2021-11-28 19:07 UTC
## What's The Problem
One of the most frustrating issues with BigNumber is that I can't prettify a BigNumber into a readable format. For example, if I was using Hardhat console to print out a BigNumber, I would get `999999999999999999292` as string format. This is difficult to read.

## Proposed Solution
If Hardhat extended BN.js with an additional function to format a BigNumber into a readable format, it would make it easier for developers to read these BigNumbers.

For example, the following code shows (I'm sure there are many ways to do this) how to convert this BigNumber to a readable format:

```javascript
bigNumber.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")

// bigNumber as a string:                  999999999999999999292 
// bigNumber using the format above:       999,999,999,999,999,999,292

```

**Comment by fvictorio** [comment] 2021-11-29 11:41
This is a good idea. The way BigNumbers are shown is certainly a big point of friction.

I think the right approach would be to leverage the inspect symbol. This [has been suggested](https://github.com/ethers-io/ethers.js/issues/1955) for ethers.js but rejected. Maybe we can do it ourselves in `hardhat-ethers`? @alcuadrado wdyt?

**Comment by fvictorio** [comment] 2021-12-02 23:26
Fixed in [`@nomiclabs/hardhat-ethers@2.0.3`](https://github.com/nomiclabs/hardhat/releases/tag/%40nomiclabs%2Fhardhat-ethers%402.0.3).

**Closed by fvictorio** 2021-12-02 23:26 UTC
Labels: package:hardhat-ethers, type:improvement

**Comment by mrthankyou** [comment] 2021-12-14 02:44
I totally forgot about this issue. I'm so happy I see you guys fixed this. Thank you so much @fvictorio and team!

**Comment by 0xthk** [comment] 2022-09-07 11:13
> Fixed in [`@nomiclabs/hardhat-ethers@2.0.3`](https://github.com/nomiclabs/hardhat/releases/tag/%40nomiclabs%2Fhardhat-ethers%402.0.3).

Hey, looks like this issue comes back after upgrade hardhat to `v2.10.0`. If I print the big number from contract call, it won't apply the formatter.

<img width="381" alt="image" src="https://user-images.githubusercontent.com/1924968/188864735-e0914fc1-803c-41d9-ac83-a48991ae9a6f.png">

**Comment by fvictorio** [comment] 2022-09-07 16:45
@0xthk which exact versions of hardhat, @nomiclabs/hardhat-ethers and ethers are you using?

**Comment by 0xthk** [comment] 2022-09-08 08:01
> @0xthk which exact versions of hardhat, @nomiclabs/hardhat-ethers and ethers are you using?

Here is the version in our package.json

    "hardhat": "^2.11.1",
    "@nomiclabs/hardhat-ethers": "^2.1.1",

**Comment by alcuadrado** [comment] 2022-09-08 14:05
`npm ls -a` or `yarn list` would be better. Can you share that?

**Comment by 0xthk** [comment] 2022-09-10 10:43
> `npm ls -a` or `yarn list` would be better. Can you share that?

Sure, here https://gist.github.com/0xthk/8c8b91cfebe2b97e729b8d86187262a4

**Comment by alcuadrado** [comment] 2022-09-10 12:50
🤯 do you have a link to the repo? Or can you post the package.json? I'm blown away by the number of versions of `ethers`  that you have.

**Comment by 0xthk** [comment] 2022-09-11 01:56
> 🤯 do you have a link to the repo? Or can you post the package.json? I'm blown away by the number of versions of `ethers` that you have.

Yeah, we are a one-year project. There are some legacies 😂 https://gist.github.com/0xthk/51e7ccb81d42918820aa28061a1bd360

**Comment by fvictorio** [comment] 2022-09-20 18:48
@0xthk can you comment the `hardhat-tenderly` plugin require/import and see if that fixes the issue?

**Comment by 0xthk** [comment] 2022-09-24 06:20
> @0xthk can you comment the `hardhat-tenderly` plugin require/import and see if that fixes the issue?

Thanks! I tried, but still no luck. I cleaned up some dependencies and this is the new version of package.json https://gist.github.com/0xthk/51e7ccb81d42918820aa28061a1bd360

**Comment by fvictorio** [comment] 2022-09-27 10:39
Hey @0xthk, sorry but I'm having a hard time trying to reproduce this. I created a project with all the dependencies in that package.json and imported all those hardhat plugins, but the prettified BigNumber still works for me. If you can share the repo where this is happening or, even better, create a minimal reproduction example, I'll take another look.

Another thing you can try is to require the `@nomiclabs/hardhat-ethers` at the top of your config. That way it will be the first plugin to be loaded, and it should do the right thing (or that's what I would expect).
