### ISSUE TITLE
Error occured when 'npx hardhat test' a single file

### ISSUE THREAD

**Issue by RutaTang** [nomiclabs/hardhat#2243] opened 2022-01-11 06:49 UTC
Using hardhat 2.8.2, when try to run a single file test, "Error: Cannot find module" happens.

I start a new project and error still exists, the following are exactly my steps:
1. `npm init --yes`
2. `npm install --save-dev hardhat`
3. `npx hardhat`, choose the "Create an advanced sample project" option
4. `npx hardhat test`, works good and no error
5. `npx hardhat test ./test/sample-test.js`, **afetr test cases are completed, an error happens "Error: Cannot find module './test/sample-test.js'"**

**Comment by kanej** [comment] 2022-01-11 10:02
Hey @RutaTang, thanks for the steps, I was able to reproduce locally.

If you run `npx hardhat test test/sample-test.js` you will avoid the error. Why the `npx hardhat test ./test/sample-test.js` formulation errors is an open issue, so I am going to close this issue as a duplicate of https://github.com/nomiclabs/hardhat/issues/2220.

**Closed by kanej** 2022-01-11 10:02 UTC
